### ISSUE TITLE
[feature] Add 13.1 support for apple-clang in settings.yml

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10801]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I've upgraded AppleClang on my mac, and I see these errors in CMake based recipes:

```
CMake Error at conanbuildinfo.cmake:402 (message):
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:

  Compiler version specified in your conan profile: 13.0

  Compiler version detected in CMake: 13.1

  Please check your conan profile settings (conan profile show
  [default|your_profile_name])

  P.S.  You may set CONAN_DISABLE_CHECK_COMPILER CMake variable in order to
  disable this check.
Call Stack (most recent call first):
  conanbuildinfo.cmake:506 (conan_error_compiler_version)
  conanbuildinfo.cmake:591 (check_compiler_version)
  conanbuildinfo.cmake:141 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)
```

I'm also wondering if adding major only versions would make sense (as gcc or clang)?

For example:

```yml
    apple-clang: &apple_clang
        version: ["5", "5.0", "5.1", "6", "6.0", "6.1", "7", "7.0", "7.3",
                  "8", "8.0", "8.1", "9", "9.0", "9.1", "10", "10.0",
                  "11", "11.0", "12", "12.0", "13", "13.0", "13.1"]
```

I've also tried to set `CONAN_DISABLE_CHECK_COMPILER=ON` in profile, but it doesn't help:

```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
[options]
[build_requires]
[env]
CONAN_DISABLE_CHECK_COMPILER=ON
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```
