### ISSUE TITLE
[bug] Apple-clang 13.1 and Catalyst

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10825]
Conan is injecting the `--target=x86_64-apple-ios-macabi` to CXXFLAGS and it is not valid anymore. 
The compiler 13.1 requires a version for ios specified in the tuple: `--target=x86_64-apple-ios13.1-macabi`.
Looks like the minimum version working is 13.1:
```
static VersionTuple minimumMacCatalystDeploymentTarget() {
  return VersionTuple(13, 1);
}
```
And it is very likely it is talking about the iOS version, but it might be convenient to model this with a subsetting of the "catalyst" 
like "ios_version"?

```
Macos:
        version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14", "10.15", "11.0", "13.0"]
        sdk: [None, "macosx"]
        subsystem:  
            None
            catalyst:
                ios_version: ["7.0", "7.1", "8.0", "8.1", "8.2", "8.3", "9.0", "9.1", "9.2", "9.3", "10.0", "10.1", "10.2", "10.3", "11.0", "11.1", "11.2", "11.3", "11.4", "12.0", "12.1", "12.2", "12.3", "12.4", "13.0", "13.1", "13.2", "13.3", "13.4", "13.5", "13.6"]    

```
Note also that apparently, this new version overrides the specified flag `-mios-version-min` according to this warning:

```
clang: warning: overriding '-mios-version-min=12.0' option with '--target=arm64-apple-ios13.1-macabi' [-Woverriding-t-option]
```

Unskip the two tests marked with:

`@pytest.mark.xfail(reason="Disabled until fix apple-clang 13.1 and --target value for catalyst")`
