### ISSUE TITLE
[question] SHORT DESCRIPTION

### ISSUE THREAD

**Issue by jellespijker** [conan-io/conan#10894]
I'm trying to use Conan as an alternative to managing our Python dependency modules. But I can't figure out a nice way to append the downloaded python module `py` files to the `PYTHONPATH` such that consumer packages might use these. I currently got it to work using `user_info` but I think using it like this is far from ideal. I would rather apply the environment of all dependencies.

I'm probably missing something very obvious and any help is appreciated.

`conanfile.py`
```python
from pathlib import Path
from conan import ConanFile
from conan.tools.files import files

required_conan_version = ">=1.33.0"


class TomlConan(ConanFile):
    name = "toml"
    description = "Python Library for Tom's Obvious, Minimal Language"
    topics = ("conan", "python", "pypi", "pip")
    license = "MIT"
    homepage = "https://github.com/uiri/toml"
    url = "https://github.com/uiri/toml"
    settings = "os", "compiler", "build_type", "arch"
    build_policy = "missing"
    requires = "cpython/[>=2.6.0]@python/stable"
    no_copy_source = True

    @property
    def _site_packages(self):
        return "site-packages"

    def source(self):
        files.get(self, **self.conan_data["sources"][self.version], destination = self._site_packages)

    def package(self):
        self.copy("*", src = self._site_packages, dst = self._site_packages)

    def package_info(self):
        self.env_info.PYTHONPATH = Path(self.package_folder, self._site_packages)
        self.user_info.pythonpath = Path(self.package_folder, self._site_packages)

    def package_id(self):
        self.info.header_only()
```
`conandata.yml`
```yaml
sources:
  "0.10.1":
    "url": "https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl"
    "sha256": "bda89d5935c2eac546d648028b9901107a595863cb36bae0c73ac804a9b4ce88"
  "0.10.2":
    "url": "https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl"
    "sha256": "806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b"
```

`conanfile.py` in the `test_package` directory
```
from conans import tools
from conan import ConanFile


class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "json", "virtualenv_python"

    def test(self):
        python_path = [self.deps_user_info[dep].pythonpath for dep in self.deps_user_info if hasattr(self.deps_user_info[dep], 'pythonpath')]
        path_sep = ";" if self.settings.get_safe("os") == "Windows" else ";"
        with tools.environment_append({"PYTHONPATH": path_sep.join(python_path)}):
            self.run(f"{self.deps_user_info['cpython'].python} -c 'import sys; print(sys.path)'")
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
