### ISSUE TITLE
[bug] tools.get() errors out if strip_root=True on some tarballs, likely due to hardlinks 

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#11065]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20
  * Compiler+version: - 
  * Conan version: 1.47.0
  * Python version: 3.8.10

I'm trying to package the precompiled toolchain that arm provides on their website
```
https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf.tar.xz
```
Since Conan can't resolve the redirection (https://github.com/conan-io/conan/issues/9036) I'm using this link instead as sources:
```
https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf.tar.xz
```
And just in case this is my full `conandata.yml`:
```
sources:
  "11.2-1.0":
    # "https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf.tar.xz"
    # The URL above (listed on arm's website) will redirect to the one below. For some reason conan can't handle this redirection.
    # It seems to be an issue on the arm webpage that they refuse to fix: https://github.com/conan-io/conan/issues/9036
    url: "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf.tar.xz"
    sha256: "c254f7199261fe76c32ef42187502839bda7efad0a66646cf739d074eff45fad"
```

On my `conanfile.py` I have a very basic `source()`  method where I set the very handy `strip_root` argument to `True`. Ignore the `filename` argument.
```
    def source(self):
        tools.get(**self.conan_data["sources"][self.version], filename="gcc.tar.xz", strip_root=True)
```
This errors out with the following message:

```
Downloading gcc.tar.xz completed [104020.39k]                                            

ERROR: toolchainArm32/11.2-1.0@eric/dev: Error in source() method, line 24
	tools.get(**self.conan_data["sources"][self.version], filename="gcc.tar.xz", strip_root=True)
	KeyError: "linkname 'gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf/arm-none-linux-gnueabihf/libc/usr/bin/getconf' not found"
```
That file is there, but seems to have hardlinks.
```
$ find -name getconf             
./arm-none-linux-gnueabihf/libc/usr/bin/getconf
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf
$ ls -i ./arm-none-linux-gnueabihf/libc/usr/bin/getconf
25321169 ./arm-none-linux-gnueabihf/libc/usr/bin/getconf
 $ find . -inum 25321169        
./arm-none-linux-gnueabihf/libc/usr/bin/getconf
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf/POSIX_V6_ILP32_OFFBIG
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf/POSIX_V7_ILP32_OFF32
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf/XBS5_ILP32_OFFBIG
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf/POSIX_V6_ILP32_OFF32
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf/XBS5_ILP32_OFF32
./arm-none-linux-gnueabihf/libc/usr/libexec/getconf/POSIX_V7_ILP32_OFFBIG
```

It looks like another dev came across the same issue, but didn't report it (or I missed the bug report). See https://github.com/conan-io/conan-center-index/blob/master/recipes/libxml2/all/conanfile.py#L108

This file also seems to be a hardlink, so this theory is worth investigating:
```
$ find -name ambig_name-class.xml       
./test/relaxng/ambig_name-class.xml
 $ ls -i ./test/relaxng/ambig_name-class.xml                                               
19019810 ./test/relaxng/ambig_name-class.xml
 $ find . -inum 19019810                   
./test/relaxng/ambig_name-class.xml
./test/relaxng/ambig_name-class2.rng
```
