### ISSUE TITLE
[question] How can I ensure local Conan profile is correctly configured in github actions workflow? os_build attribute becomes "Linux" for macOS?

### ISSUE THREAD

**Issue by cyreon** [conan-io/conan#11345]
Could you please suggest why github actions doesn't recognize os_build and compiler correctly for macos-latest? For some reason conan sees Linux/gcc configuration. I wouldn't be surprised if macos-latest configuration uses a physical linux machine in github, but it is just an assumption (I might ask github guys too). Should I explicitly specify in a conan profile how I want to build the project as I already have done before in the below sample? Any help is appreciated and I am looking forward to hear back from you. So far I like Conan very much!

```
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
       include:
         - name: linux
           os: ubuntu-latest
#           compiler: gcc
#           compiler_version: 9
#           compiler_libcxx: libstdc++11

         - name: mac
           os: macos-latest
#           compiler: apple-clang
#           compiler_version: 13.0
#           compiler_libcxx: libc++

         - name: windows
           os: windows-latest
#           compiler: Visual Studio
#           compiler_version: 16
#           compiler_libcxx: cppstd

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Retrieve current branch name
        id: this_branch
        run: |
          echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      # For speeding up the build, let's create a cache for conan packages.
      # A new branch will create a copy of the master cache,
      # but the master cache isn't updated until a merge to the master branch.
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.this_branch.outputs.name }}
          restore-keys: |
            conan-package-cache-master

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name: Install/Upgrade Conan
        run: pip3 install --upgrade conan

      - name: Create build directory
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure
        working-directory: ${{ github.workspace }}/build
        run: |
          conan install .. -s build_type=${{ env.BUILD_TYPE }} --build missing

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: conan build ..

      - name: Package
        working-directory: ${{ github.workspace }}/build
        run: conan package ..

      - name: Retrieve artifact information
        working-directory: ${{ github.workspace }}/build
        id: artifact_data
        run: |
          echo "::set-output name=name::$(cat artifact_name.txt)"
          echo "::set-output name=path::$(cat artifact_path.txt)"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifact_data.outputs.name }}
          path: ${{ steps.artifact_data.outputs.path }}

```

You can find the corresponding logs here:
```
Run conan install .. -s build_type=Release --build missing
  conan install .. -s build_type=Release --build missing
  shell: /bin/bash -e {0}
  env:
    BUILD_TYPE: Release
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.10.4/x64
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (project-init-cpp/0.1): Installing package
Requirements
    gtest/1.11.0 from 'conancenter' - Cache
Packages
    gtest/1.11.0:7320405f83ec32d8556b524cdda87ee295bb7b84 - Cache

Cross-build from 'Macos:x86_64' to 'Linux:x86_64'
Installing (downloading, building) binaries...
gtest/1.11.0: Already installed!
conanfile.py (project-init-cpp/0.1): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (project-init-cpp/0.1): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (project-init-cpp/0.1): Generator txt created conanbuildinfo.txt
conanfile.py (project-init-cpp/0.1): Aggregating env generators
conanfile.py (project-init-cpp/0.1): Generated conaninfo.txt
conanfile.py (project-init-cpp/0.1): Generated graphinfo
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
