### ISSUE TITLE
[question] error on concurrent package creation

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan#11919]
Hello,

I'm using latest conan 1.51.3 on Linux and Gitlab CI with several jobs building binary for differents target.
But when calling "conan create" or "conan export-pkg" I get randomly following error:

```
error: unrecognized arguments: Settings already up to date
```

For now I use "export-pkg" command with "conan install" and "conan build" called before, to limit concurrency issue with conan cache and also to be able to make Sonar code quality analysis from git clone instead of having build done in cache.
But I have always these random errors at "export-pkg" command  invocation.
The lock file doesn't seems used with this command.
And as documented in https://docs.conan.io/en/latest/mastering/custom_cache.html#concurrency, I don't want to use a cache by CI job, which is very not efficient.

Do you have some tips to avoid this kind concurrency issue?

Regards.

**Comment by EstebanDugueperoux2** [comment]
I get this issue even with latest conan (1.54.0).

**Comment by EstebanDugueperoux2** [comment]
According to https://stackoverflow.com/questions/17118999/python-argparse-unrecognized-arguments the "unrecognized arguments" message comes from argparse python library.
Then it seems a bug in the use of this library.
Indeed in https://github.com/conan-io/conan/blob/1987d00089a8ec80540a98468360493ce17a354a/conans/client/command.py#L1034 we see `parser.parse_args(*args)` instead of `parser.parse_args()` as documented in https://docs.python.org/3/library/argparse.html

Someone from conan team could help me in this very anoying bug?
@ericLemanissier do you have an advise about that?

Regards.

**Comment by memsharded** [comment]
Hi @EstebanDugueperoux2 

Can you please clarify about:

>Then it seems a bug in the use of this library.
we see parser.parse_args(*args) instead of parser.parse_args() as documented in

From https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_args, it seems a valid use case, and not a bug in the usage of the library. Not only valid, but even necessary when processing sub-commands or nested commands (with nested args)

**Comment by EstebanDugueperoux2** [comment]
Hi @memsharded,

Thanks for your quick reply.
I try to understand my random bug and try to understand what in argparse library is not good.
I reproduce this issue only randomly in a Gitlab CI context using official conan Docker images.

My Gitlab CI job consists of:

```
myJob:
  image: conanio/gcc8-ubuntu16.04
  variables:
    CHANNEL: testing
    OPTIONS: --profile:build .conan/profiles/gcc8 --profile:host .conan/profiles/gcc8 -s myPackage:build_type=Debug -o myPackage:test=True
  stage: build
  script:
    - export PACKAGE_VERSION=`conan inspect . --raw version`
    - conan install . --build missing $OPTIONS
    - conan build .
    - conan export-pkg . unite/$CHANNEL --force
    - conan test test_package myPackage/$PACKAGE_VERSION@unite/$CHANNEL $OPTIONS
    - conan upload myPackage/$PACKAGE_VERSION@unite/$CHANNEL --confirm --parallel --all -r $ARTIFACTORY_REPOSITORY
```

And at `conan export-pkg` call I get following error:

```
$ conan export-pkg . myPackage/$PACKAGE_VERSION@unite/$CHANNEL --force
Migration: Settings already up to date
WARN: Migration: Updating settings.yml
usage: conan export-pkg [-h] [-bf BUILD_FOLDER] [-f] [-if INSTALL_FOLDER]
                        [-pf PACKAGE_FOLDER] [-sf SOURCE_FOLDER] [-j JSON]
                        [-l LOCKFILE] [--lockfile-out LOCKFILE_OUT]
                        [--ignore-dirty] [-e ENV_HOST] [-e:b ENV_BUILD]
                        [-e:h ENV_HOST] [-o OPTIONS_HOST] [-o:b OPTIONS_BUILD]
                        [-o:h OPTIONS_HOST] [-pr PROFILE_HOST]
                        [-pr:b PROFILE_BUILD] [-pr:h PROFILE_HOST]
                        [-s SETTINGS_HOST] [-s:b SETTINGS_BUILD]
                        [-s:h SETTINGS_HOST] [-c CONF_HOST] [-c:b CONF_BUILD]
                        [-c:h CONF_HOST]
                        path [reference]
conan export-pkg: error: unrecognized arguments: Settings already up to date 21.0.0@unite/testing
ERROR: Exiting with code: 2
```

Any clue to analysis this issue is welcome.

Regards.
