### ISSUE TITLE
[question] how to get options from conandata.yml

### ISSUE THREAD

**Issue by unfor19** [conan-io/conan#12285]
Hi there,
Is there a way to fetch [options](https://docs.conan.io/en/1.50/mastering/conditional.html#constrain-settings-and-options) from the [conandata.yml](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html) file?

I've tried the following, though I keep getting errors regarding the "type of option", I think it's something related to `assertion` tests that `options` perform during `__init__`.

My attempt is in the code snippet below, I can't assign a dictionary to the `self.options` property.

`conanfile.py`
```python
from pathlib import Path
import pathlib
from conans import CMake, ConanFile, tools
from conans.model.options import OptionsValues, PackageOptions, PackageOptionValues

import os

class MyPackage(ConanFile):
    name = "my-package"
    settings = "os", "build_type", "compiler", "arch"

    @staticmethod
    def _merge_dicts(a, b, path=None):
        """
        Source: https://stackoverflow.com/questions/7204805/how-to-merge-dictionaries-of-dictionaries
        """
        if path is None:
            path = []
        for key in b:
            if key in a:
                if isinstance(a[key], dict) and isinstance(b[key], dict):
                    MyPackage._merge_dicts(a[key], b[key], path + [str(key)])
                elif a[key] == b[key]:
                    pass  # same leaf value
                else:
                    raise Exception('Conflict at %s' %
                                    '.'.join(path + [str(key)]))
            else:
                a[key] = b[key]
        return a


    def config_options(self):
        self.output.info("Executing config_options() method")
        target_os = str(self.settings.os).lower()
        opts_final = dict()
        opts_all = dict(self.conan_data["options"]["all"])
        opts_os = dict()
        if target_os in self.conan_data["options"]:
            opts_os = dict(self.conan_data["options"][target_os])
            opts_final = MyPackage._merge_dicts(opts_all, opts_os)
        else:
            opts_final = opts_all

        for pkg in opts_final:
            for pkg_attr in opts_final[pkg]:
                print(pkg, pkg_attr, opts_final[pkg][pkg_attr])
```

`conandata.yml`
```yml
options:
  all:
    boost:
      without_locale: True
      without_log: True
      without_stacktrace: True
    ffmpeg:
      with_libx264: False
      with_libx265: False
      with_libiconv: False
      with_lzma: False
      with_zlib: False
  linux:
    boost:
      without_python: False
    ffmpeg:
      with_pulse: False
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

@memsharded - I've implemented the new `conandata.yml` with `requirements` and `tool_requires` and it works like a charm. Now I'm greedy and I want to include `options` in it. Help? :)
