### ISSUE TITLE
[feature] Add support to validate checksum in apply_conandata_patches

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12455]
So far, [apply_conandata_patches](https://github.com/conan-io/conan/blob/d3a6b69f1f2f12cda384ac96662f87f00aa869d7/conan/tools/files/patches.py#L66) ignores any form of checksum, however, several [downloads](https://docs.conan.io/en/latest/reference/conanfile/tools/files/downloads.html) methods support it.

It would be great if `apply_conandata_patches` could validate `sha256` according to the current [conandata.yml format](https://github.com/conan-io/conan-center-index/blob/master/docs/conandata_yml_format.md#patches) adopted in ConanCenterIndex.

The format is an extension to the original [conandata.yml](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html) from docs, but allowing better information related to any patch which should be applied.

As generic example:

```
sources:
  "1.2.0":
    - url: "https://foobar.org/downloads/1.2.0.tar.gz"
      sha256: "4c43d0ea98669e3d6fbb5810cc47b19adaf88cabb1421b488aa306b08c434131"
patches:
  "1.2.0":
    - patch_file: "patches/1.2.0-002-link-core-with-find-library.patch"
      patch_description: "Link CoreFoundation and CoreServices with find_library"
      patch_type: "portability"
      patch_source: "https://a-url-to-a-pull-request-mail-list-topic-issue-or-question"
      sha256: "qafe4rq54533qa43esdaq53ewqa5"
```

The `apply_conandata_patches` should use [check_sha256](https://docs.conan.io/en/latest/reference/conanfile/tools/files/checksum.html#conan-tools-files-check-sha256) and check the field `sha256` with the `patch_file` content.

Related to https://github.com/conan-io/conan-center-index/issues/13870

- [ X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
