### ISSUE TITLE
[question] Dependency override/force flag behavior

### ISSUE THREAD

**Issue by mzukovec** [conan-io/conan#13457]
### What is your question?

Not sure if this is normal behavior or a bug. Note: this is just a theoretical example.
I want to install Eigen via the following conanfile:
<details>
  <summary>conanfile.py</summary>

  ```
  from conan import ConanFile

  class ProjectDeps(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def requirements(self):
        self.requires("eigen/3.4.0")

  ```

</details>

If I query dependency graph, everything works as expected; Eigen is found on a dependency graph \
`conan graph .`

<details>
  <summary>Log 1</summary>

  ```
  ======== Computing dependency graph ========
Graph root
    conanfile.py: C:\Users\zukov\Documents\tmp\conan_override\conanfile.py
Requirements
    eigen/3.4.0#1bc43ded5116678f202a75aa887ef142 - Cache

======== Computing necessary packages ========
Requirements
    eigen/3.4.0#1bc43ded5116678f202a75aa887ef142:da39a3ee5e6b4b0d3255bfef95601890afd80709#3d4cb80b19cf7de2d5fd0a2413dab746 - Cache

======== Basic graph information ========
:
  ref:
  id: 0
  recipe: Consumer
  package_id: 0ce4f92cce478a79e6c898ff49826d4f663e54a9
  prev: None
  build_id: None
  binary: None
  invalid_build: False
  revision_mode: hash
  package_type: unknown
  settings:
    os: Windows
    arch: x86_64
    compiler: msvc
    compiler.runtime: dynamic
    compiler.runtime_type: Release
    compiler.update: 4
    compiler.version: 193
    build_type: Release
  system_requires:
  options:
  recipe_folder: C:\Users\zukov\Documents\tmp\conan_override
  source_folder: None
  build_folder: None
  package_folder: None
  cpp_info:
    root:
      includedirs: ['include']
      srcdirs: None
      libdirs: ['lib']
      resdirs: None
      bindirs: ['bin']
      builddirs: None
      frameworkdirs: None
      system_libs: None
      frameworks: None
      libs: None
      defines: None
      cflags: None
      cxxflags: None
      sharedlinkflags: None
      exelinkflags: None
      objects: None
      sysroot: None
      requires: None
      properties: None
  label: conanfile.py
  context: host
  test: False
  requires:
    1: eigen/3.4.0#1bc43ded5116678f202a75aa887ef142
eigen/3.4.0#1bc43ded5116678f202a75aa887ef142:
  ref: eigen/3.4.0#1bc43ded5116678f202a75aa887ef142
  id: 1
  recipe: Cache
  package_id: da39a3ee5e6b4b0d3255bfef95601890afd80709
  prev: 3d4cb80b19cf7de2d5fd0a2413dab746
  build_id: None
  binary: Cache
  invalid_build: False
  url: https://github.com/conan-io/conan-center-index
  license: ('MPL-2.0', 'LGPL-3.0-or-later')
  description: Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
  topics: ('algebra', 'linear-algebra', 'matrix', 'vector', 'numerical')
  homepage: http://eigen.tuxfamily.org
  revision_mode: hash
  package_type: unknown
  settings:
    os: Windows
    arch: x86_64
    compiler: msvc
    compiler.runtime: dynamic
    compiler.runtime_type: Release
    compiler.update: 4
    compiler.version: 193
    build_type: Release
  system_requires:
  options:
    MPL2_only: False
  recipe_folder: C:\Users\zukov\.conan2\p\eigenf485e38d6dd8b\e
  source_folder: None
  build_folder: None
  package_folder: None
  cpp_info:
    root:
      includedirs: ['include']
      srcdirs: None
      libdirs: ['lib']
      resdirs: None
      bindirs: ['bin']
      builddirs: None
      frameworkdirs: None
      system_libs: None
      frameworks: None
      libs: None
      defines: None
      cflags: None
      cxxflags: None
      sharedlinkflags: None
      exelinkflags: None
      objects: None
      sysroot: None
      requires: None
      properties: None
  label: eigen/3.4.0
  context: host
  test: False
  requires:
  ```

</details>

If I set the requirement flag to `override=True`, dependency graph becomes empty:
<details>
  <summary>conanfile.py</summary>

  ```
  from conan import ConanFile

  class ProjectDeps(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def requirements(self):
        self.requires("eigen/3.4.0", override=True)

  ```

</details>

`conan graph info .`

<details>
  <summary>Log 2</summary>

  ```
  ======== Computing dependency graph ========
Graph root
    conanfile.py: C:\Users\zukov\Documents\tmp\conan_override\conanfile.py

======== Computing necessary packages ========

======== Basic graph information ========
:
  ref:
  id: 0
  recipe: Consumer
  package_id: da90b1c0a142807d643d75e45065afd4c82f99ca
  prev: None
  build_id: None
  binary: None
  invalid_build: False
  revision_mode: hash
  package_type: unknown
  settings:
    os: Windows
    arch: x86_64
    compiler: msvc
    compiler.runtime: dynamic
    compiler.runtime_type: Release
    compiler.update: 4
    compiler.version: 193
    build_type: Release
  system_requires:
  options:
  recipe_folder: C:\Users\zukov\Documents\tmp\conan_override
  source_folder: None
  build_folder: None
  package_folder: None
  cpp_info:
    root:
      includedirs: ['include']
      srcdirs: None
      libdirs: ['lib']
      resdirs: None
      bindirs: ['bin']
      builddirs: None
      frameworkdirs: None
      system_libs: None
      frameworks: None
      libs: None
      defines: None
      cflags: None
      cxxflags: None
      sharedlinkflags: None
      exelinkflags: None
      objects: None
      sysroot: None
      requires: None
      properties: None
  label: conanfile.py
  context: host
  test: False
  requires:
  ```

</details>

If I set the requirement flag to `force=True`, dependency graph includes Eigen once again:
<details>
  <summary>conanfile.py</summary>

  ```
  from conan import ConanFile

  class ProjectDeps(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def requirements(self):
        self.requires("eigen/3.4.0", force=True)

  ```

</details>

`conan graph info .`

<details>
  <summary>Log 3</summary>

  ```
  ======== Computing dependency graph ========
Graph root
    conanfile.py: C:\Users\zukov\Documents\tmp\conan_override\conanfile.py
Requirements
    eigen/3.4.0#1bc43ded5116678f202a75aa887ef142 - Cache

======== Computing necessary packages ========
Requirements
    eigen/3.4.0#1bc43ded5116678f202a75aa887ef142:da39a3ee5e6b4b0d3255bfef95601890afd80709#3d4cb80b19cf7de2d5fd0a2413dab746 - Cache

======== Basic graph information ========
:
  ref:
  id: 0
  recipe: Consumer
  package_id: 0ce4f92cce478a79e6c898ff49826d4f663e54a9
  prev: None
  build_id: None
  binary: None
  invalid_build: False
  revision_mode: hash
  package_type: unknown
  settings:
    os: Windows
    arch: x86_64
    compiler: msvc
    compiler.runtime: dynamic
    compiler.runtime_type: Release
    compiler.update: 4
    compiler.version: 193
    build_type: Release
  system_requires:
  options:
  recipe_folder: C:\Users\zukov\Documents\tmp\conan_override
  source_folder: None
  build_folder: None
  package_folder: None
  cpp_info:
    root:
      includedirs: ['include']
      srcdirs: None
      libdirs: ['lib']
      resdirs: None
      bindirs: ['bin']
      builddirs: None
      frameworkdirs: None
      system_libs: None
      frameworks: None
      libs: None
      defines: None
      cflags: None
      cxxflags: None
      sharedlinkflags: None
      exelinkflags: None
      objects: None
      sysroot: None
      requires: None
      properties: None
  label: conanfile.py
  context: host
  test: False
  requires:
    1: eigen/3.4.0#1bc43ded5116678f202a75aa887ef142
eigen/3.4.0#1bc43ded5116678f202a75aa887ef142:
  ref: eigen/3.4.0#1bc43ded5116678f202a75aa887ef142
  id: 1
  recipe: Cache
  package_id: da39a3ee5e6b4b0d3255bfef95601890afd80709
  prev: 3d4cb80b19cf7de2d5fd0a2413dab746
  build_id: None
  binary: Cache
  invalid_build: False
  url: https://github.com/conan-io/conan-center-index
  license: ('MPL-2.0', 'LGPL-3.0-or-later')
  description: Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
  topics: ('algebra', 'linear-algebra', 'matrix', 'vector', 'numerical')
  homepage: http://eigen.tuxfamily.org
  revision_mode: hash
  package_type: unknown
  settings:
    os: Windows
    arch: x86_64
    compiler: msvc
    compiler.runtime: dynamic
    compiler.runtime_type: Release
    compiler.update: 4
    compiler.version: 193
    build_type: Release
  system_requires:
  options:
    MPL2_only: False
  recipe_folder: C:\Users\zukov\.conan2\p\eigenf485e38d6dd8b\e
  source_folder: None
  build_folder: None
  package_folder: None
  cpp_info:
    root:
      includedirs: ['include']
      srcdirs: None
      libdirs: ['lib']
      resdirs: None
      bindirs: ['bin']
      builddirs: None
      frameworkdirs: None
      system_libs: None
      frameworks: None
      libs: None
      defines: None
      cflags: None
      cxxflags: None
      sharedlinkflags: None
      exelinkflags: None
      objects: None
      sysroot: None
      requires: None
      properties: None
  label: eigen/3.4.0
  context: host
  test: False
  requires:
  ```

</details>

In this case, override didn't override anything in practice, but shouldn't Eigen be kept on dependency graph nevertheless? If not, why is it kept in case of `force=True`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

# EDIT:
I'm using conan 2.0.1
