### ISSUE TITLE
Consider adding gcc/clang sanitizers to the model

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1346]
There are different sanitizers in gcc/clang that affect the final binary.
When you build with one sanitizer, it is typical that the whole project must use it. Then it sounds, that it should be a children of the ``gcc`` and ``clang`` compilers.

A possible proposal could be:

```
gcc:
    thread_sanitizer: None, True
    memory_sanitizer: None, True
     ....
```
It will use: ``self.compiler.thread_sanitizer=True`` syntax

**Comment by lasote** [comment]
Or if the combination of many is not common (please feedback) could be a single subsetting with values:

```
  gcc:
      sanitizer: None, memory, thread, leak, thread_leak
```

If depends on the possible/allowed combinations, if it's crazy would be better to go with @memsharded way.

**Comment by mropert** [comment]
The [Clang Manual](https://clang.llvm.org/docs/UsersManual.html#controlling-code-generation) can give some insights.
There are a checks available for `-f[no-]sanitize`:
> -fsanitize=address: AddressSanitizer, a memory error detector.
> -fsanitize=thread: ThreadSanitizer, a data race detector.
> -fsanitize=memory: MemorySanitizer, a detector of uninitialized reads. Requires instrumentation of all program code.
> -fsanitize=undefined: UndefinedBehaviorSanitizer, a fast and compatible undefined behavior checker.
> -fsanitize=dataflow: DataFlowSanitizer, a general data flow analysis.
> -fsanitize=cfi: control flow integrity checks. Requires -flto.
> -fsanitize=safe-stack: safe stack protection against stack-based memory corruption errors.

Also an interesting note:

> It is not possible to combine more than one of the -fsanitize=address, -fsanitize=thread, and -fsanitize=memory checkers in the same program.

GCC hass [less but similar options](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html):
> -fsanitize=address
> -fsanitize=kernel-address
> -fsanitize=thread
> -fsanitize=leak
> -fsanitize=undefined

The `kernel-address` check enables the [Linux Kernel AddressSanitizer](https://github.com/google/kasan/wiki), probably not useful in our case.
The `leak` check enables the [LeakSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer) on Linux x86_64. It is also available on Clang, but implicit (enabled when `-fsanitize=address` is used).
As with Clang, `address` and `thread` cannot be used at the same time.

Based on that, I think I'll go towards @memsharded solution since (at least with Clang) there can be quite a lot of combinations.

Here's a suggestion:
```
gcc:
   address_sanitizer: None, True
   thread_sanitizer: None, True
   leak_sanitizer: None, True
   undefined_sanitizer: None, True
clang:
   address_sanitizer: None, True
   thread_sanitizer: None, True
   memory_sanitizer: None, True
   undefined_sanitizer: None, True
   dataflow_sanitizer: None, True
   cfi_sanitizer: None, True
   safe_stack_sanitizer: None, True
apple-clang:
   # Same as clang
```

We could simplify GCC a bit by making `leak_sanitizer` implied when `address_sanitizer` is active (like Clang does) but I'm not sure that logic should be defined in Conan.
Another option would be to regroup `address`, `thread` and `memory` in the same setting since they are mutually exclusive but that would create one list setting (`[None, address, memory, thread`]) and a some booleans (`undefined`, `dataflow`, `cfi`, `safe_stack` and possibly `leak`) which is not exactly consistent.
