### ISSUE TITLE
[bug] conan error“cannot import name 'ConanFile'

### ISSUE THREAD

**Issue by AlexandreRey** [conan-io/conan#13806]
### Environment details

* Operating System+version: W10
* Compiler+version:
* Conan version: 2.0.4
* Python version: 3.11.3

### Steps to reproduce

Hello,
When I try to download a package from the ConanCenter, I get this error.
I've just imputed the command line written on the page : 
conan download openssl/3.0.1@#86af37e68312f9335a25ad9c0c5efe7c:304480252b01879c8641f79a653b593b8f26cf9f --remote conancenter
for information, I've installed Conan using the windows64 .exe

### Logs

conan download openssl/3.0.1@#86af37e68312f9335a25ad9c0c5efe7c:304480252b01879c8641f79a653b593b8f26cf9f --remote conancenter
Downloading recipe 'openssl/3.0.1#86af37e68312f9335a25ad9c0c5efe7c'
Decompressing conan_export.tgz
ERROR: Error loading conanfile at 'C:\Users\rey.a\.conan2\p\opensde2ad0933376a\e\conanfile.py': Unable to load conanfile in C:\Users\rey.a\.conan2\p\opensde2ad0933376a\e\conanfile.py
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\rey.a\.conan2\p\opensde2ad0933376a\e\conanfile.py", line 3, in <module>
    from conans import ConanFile, AutoToolsBuildEnvironment, tools
ImportError: cannot import name 'ConanFile'

**Comment by franramirez688** [comment]
Hi @AlexandreRey 

Yeah, this is not a bug but expected behavior. It seems that you're trying to download a binary built by a Conan 1.x recipe which is incompatible with 2.x ones.

You could easily check the binaries available for any package using the `conan list` command:

```
$ conan list "openssl/3.0.1:*" -r conancenter
conancenter
  openssl
    openssl/3.0.1
      revisions
        86af37e68312f9335a25ad9c0c5efe7c (2022-06-29 16:09:44 UTC)
          packages
```
As you can see, the revision is there but not any binary listed after the `packages` line.

FYI, It seems that we have some binaries available for `openssl>=3.0.5`. For instance:

```
$ conan download openssl/3.0.8@#394c3c3c0d0d64b9574621b98b7bcda3:0f0f6fbd7fdffc1b1c00585a47779b27aad18b54 -r conancenter
```

UPDATED:

I did not say that this command `$ conan list "openssl/3.0.1:*" -r conancenter` is showing the package IDs for the LATEST recipe revision. See more information about [conan list command](https://docs.conan.io/2/reference/commands/list.html).

More clarifications about Conan recipe revisions (__name/version@user/channel#RECIPE_REVISION:PACKAGE_ID__). Any Conan recipe can have several recipe revisions for one single version, i.e., any recipe, like `openssl/x.x.x`, could have a version with several recipe revisions, a 1.x-only and the latest one with both 1-x and 2.x compatible.
In this case, it seems that `openssl/3.0.1` was not ported to Conan 2.x compatible syntax at all (check the latest revision [here](https://conan.io/center/openssl?version=3.0.1&tab=recipe)), so it has no recipe revisions compatible with Conan 2.x.

**Comment by franramirez688** [comment]
Hi @AlexandreRey 

Also, I just checked the [available versions for openssl](https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/3.x.x/conandata.yml) and the 3.0.1 is not listed anymore:

```yaml
sources:
  3.1.0:
    url:
      - "https://www.openssl.org/source/openssl-3.1.0.tar.gz"
    sha256: aaa925ad9828745c4cad9d9efeb273deca820f2cdcf2c3ac7d7c1212b7c497b4
  3.0.8:
    url:
      - "https://www.openssl.org/source/openssl-3.0.8.tar.gz"
      - "https://github.com/openssl/openssl/releases/download/openssl-3.0.8/openssl-3.0.8.tar.gz"
    sha256: 6c13d2bf38fdf31eac3ce2a347073673f5d63263398f1f69d0df4a41253e4b3e
  3.0.7:
    url:
      - "https://www.openssl.org/source/openssl-3.0.7.tar.gz"
      - "https://github.com/openssl/openssl/releases/download/openssl-3.0.7/openssl-3.0.7.tar.gz"
    sha256: 83049d042a260e696f62406ac5c08bf706fd84383f945cf21bd61e9ed95c396e
  3.0.5:
    url: https://www.openssl.org/source/openssl-3.0.5.tar.gz
    sha256: aa7d8d9bef71ad6525c55ba11e5f4397889ce49c2c9349dcea6d3e4f0b024a7a
```

That's why you cannot download it.
