### ISSUE TITLE
Travis, Bintray and Remotes

### ISSUE THREAD

**Issue by jacmoe** [conan-io/conan#1382]
I am using a couple packages from Bintray in my project, and it works "on my machine" because I have added the remote to Conan.

But I can't seem to figure out how to add the remote to Conan on Travis..

I have this in my `install.sh` :

```
pip install conan_package_tools # It install conan too
conan remote add dimi https://api.bintray.com/conan/dimi309/conan-packages
conan user -p $BINTRAY_APIKEY -r dimi jacmoe

```

I tried just with `conan user` , but then I added my Bintray API key to Travis ...

Am I not able to use other people's packages on Travis?
Or, why does the remote get ignored?

Thanks :)

**Comment by jacmoe** [comment]
Is that the right way to log into Conan/Bintray?

**Comment by jacmoe** [comment]
Probably related to #1380 ?

**Comment by memsharded** [comment]
Yes, very related to #1380. Yesterday I managed to upload to bintray from CI with:

appveyor.yml:

```yaml
build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REMOTE: myrepo 
    CONAN_REFERENCE: "HelloCi/0.1"
    CONAN_USERNAME: "memsharded"
    CONAN_CHANNEL: "testing"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_CURRENT_PAGE: VisualStudio_15_x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_CURRENT_PAGE: VisualStudio_15_x86
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_CURRENT_PAGE: VisualStudio_14_x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_CURRENT_PAGE: VisualStudio_14_x86
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_CURRENT_PAGE: VisualStudio_12_x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_CURRENT_PAGE: VisualStudio_12_x86

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - pip.exe install conan --upgrade
  - conan remote add myrepo https://api.bintray.com/conan/memsharded/myrepo
  - conan user # It creates the conan data directory

test_script:
  - python build.py
```

Now, everything is a bit messy, we are working on it to stabilize, also adding some functionality into conan-package-tools. Thanks!
