### ISSUE TITLE
Defining custom settings.yml for sanitizers

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#13981]
I already configured our `settings.yml` with sanitizer options per the doc a while back.  (BTW, why not just include these sanitization options in the default conan.io settings.yml?)

```
compiler:
    gcc: &gcc
        address_sanitizer: [None, True]
        hwaddress_sanitizer: [None, True]
        kernel_address_sanitizer: [None, True]
        thread_sanitizer: [None, True]
        undefined_behavior_sanitizer: [None, True]
        pointer_compare_sanitizer: [None, True] # only valid with address or kernel_address
        pointer_subtract_sanitizer: [None, True] # only valid with address or kernel_address
        shadow_call_stack_sanitizer: [None, True]
        leak_sanitizer: [None, True]
        stack_protector: [None, True]
        stack_check: [None, True]
    clang:
        address_sanitizer: [None, True]
        hwaddress_sanitizer: [None, True]
        thread_sanitizer: [None, True]
        memory_sanitizer: [None, True]
        undefined_behavior_sanitizer: [None, True]
```

But, I still don't know how to manage my `.conan/data` output.  As it is now, `conan install` just overwrites the dependency binaries per sanitization setting.  How does a `settings_user.yml` fix this?  Are you saying to upload different binaries to artifactory on a per-`settings.yml`-basis?  What does that look like?  I could in-theory upload the binaries to artifactory, but nobody else needs them other than me.

Oh, and `CONAN_SETTINGS_COMPILER_SANITIZER` seems not to be propagated for the conan 1.60 generator.  Is there something else I have to do to make that work?

> Even if I could do something with settings.yml, uploading and then downloading 65-package binaries that I already compiled on my macbook just because I changed a compiler flag seems wrong too.

_Originally posted by @hoyhoy in https://github.com/conan-io/conan/issues/5295#issuecomment-1564821799_
