### ISSUE TITLE
[question] How to specify settings for package dependencies?

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#14212]
### What is your question?

Hi,

I have a number of baremetal, embedded software applications, which I need to build for different hardware platforms. I am creating conan packages from each of these, using custom settings I introduced in settings_user.yml

```
os:
    baremetal:
        platform:
            E0055:
                revision: [null, "01.01", "02.02"]
            E0064:
                revision: [null, "01.01", "02.01"]
            E0065:
                revision: [null, "02.02", "03.01"]
            null:
```

Then, I want to have a "parent" package which bundles all my "child" packages. The recipe for this one is very simple at the moment:

```
class ParentPkgRecipe(ConanFile):
    name = "parent-pkg"
    version = "1.0"

    def requirements(self):
        self.requires("child-pkg-1/1.1.0")
        self.requires("child-pkg-2/1.0.4")
        self.requires("child-pkg-3/1.2.2")
```
How can I create my parent package in a way that for example:

- For `child-pkg-1/1.1.0` the build for `os.platform=E0055`, `os.platform.revision=01.01` is used
- For `child-pkg-2/1.0.4` the build for `os.platform=E0064`, `os.platform.revision=02.01` is used
- For` child-pkg-3/1.2.2` the build for `os.platform=E0065`, `os.platform.revision=03.01` is used

In other words, use specific settings to include each child. Not just apply settings to the parent and the same will be used for all childs. Actually my custom settings are not even applicable to the parent package, as it is just a bundle.

Thanks,
Luca

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide
