### ISSUE TITLE
[question]  OperatingSystem-specific patches in a CCI recipe

### ISSUE THREAD

**Issue by fpelliccioni** [conan-io/conan#14553]
### What is your question?

In an CCI recipe:
What is the proper way to store `.patch` files that should only be applied for a certain OS?

For example, given this existing `conandata.yml`:
```
patches:
  "6.3.0":
    - patch_file: "patches/0001-msvc-dumpbin-yasm-wrapper.patch"
    - patch_file: "patches/6.x.x-0001-fix-MSVC-next-prime-error.patch"
  "6.2.1":
    - patch_file: "patches/0001-msvc-dumpbin-yasm-wrapper.patch"
    - patch_file: "patches/6.x.x-0001-fix-MSVC-next-prime-error.patch"
```

Is it possible to:

```
patches:
  "6.3.0":
    - patch_file: "patches/0001-msvc-dumpbin-yasm-wrapper.patch"
    - patch_file: "patches/6.x.x-0001-fix-MSVC-next-prime-error.patch"
  "6.2.1":
    - patch_file: "patches/0001-msvc-dumpbin-yasm-wrapper.patch"
    - patch_file: "patches/6.x.x-0001-fix-MSVC-next-prime-error.patch"
  "Emscripten":
    - patch_file: "patches/0001-emscripten-specific.patch"
    - patch_file: "patches/0002-emscripten-specific.patch"
```

?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide
