### ISSUE TITLE
[question] [Conan 2] [CICD] How can I check if a recipe is up to date compared to the remote?

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#15060]
### What is your question?

We maintain our own fork of conan-center-index with custom recipes + our own server of packages. I'm working on the Conan 1 -> Conan 2 migration and I'm a bit stuck trying to figure out which packages should be rebuilt and which ones are up to date.

This is the way we do it now: on our fork of conan-center-index we also maintain a `yaml` file that just lists the packages we want, it looks like this:
```yaml
jobs:
   gtest:
     1.13.0:
       x86_64_gcc10:
       x86_64_clang12:
       aarch64:
       arm:
     1.10.0:
       x86_64_gcc10:
       x86_64_clang12:
       aarch64:
       arm:
   libjpeg-turbo:
     2.1.2:
       x86_64_gcc10:
         - "turbojpeg=False"
       x86_64_clang12:
         - "turbojpeg=False"
       aarch64:
         - "turbojpeg=False"
       arm:
         - "turbojpeg=False"
```
So we list which packages we want, which versions, for which platforms and for we also list options, if the defaults are not good for us.

In our CICD pipeline we iterate over all those recipes, export them and then try to figure out if the package needs to be built or not. We want to build the package its recipe changed or if any of its dependencies changed.

The way we do that, for example for gtest is:
```
$ conan info gtest/1.13.0 -pr:b .conanprofiles/x86_64_gcc10 -pr:h .conanprofiles/x86_64_gcc10 --build=missing --build=outdated
gtest/1.13.0: Package is up to date
```
So we know `gtest/1.13.0` can be skipped. If the recipe had changed, we would get this instead:
```
$ conan info gtest/1.13.0 -pr:b .conanprofiles/x86_64_gcc10 -pr:h .conanprofiles/x86_64_gcc10 --build=missing --build=outdated
gtest/1.13.0
```
So we know that the recipe changed and we need to build the package. (we actually use the `--json` argument on `conan info` but the idea is the same).

I can't replicate this on Conan 2 since the `conan info` no longer exists. I've tried with `conan graph` but I can't seem to get a similar behavior.
I considered replacing our yaml with just a dummy `conanfile.py` that requires every package we want and then use `conan graph build-order` to get a list of what needs to be built and in which order, but that would break our ability to support multiple versions of the same package at the same time.

Do you guys have any suggestion?

Thanks,

Eric.  

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide
