### ISSUE TITLE
[question] how to use detect_libcxx

### ISSUE THREAD

**Issue by h-2** [conan-io/conan#15168]
### What is your question?

Maybe this is a stupid question, but how do I use `detect_libcxx()` ?

The documentation on https://docs.conan.io/2.0/reference/config_files/profiles.html mentions
```
`detect_libcxx(compiler, version)`: returns C++ standard library as a string (e.g., “libstdc++”, “libc++”).
```

But I cannot make it work. Googling for `conan2 "detect_libcxx"` also yields exactly one result(the aforementioned page). This is the profile_template (other things are filled in by other profiles that include this one):

```toml
{% set compiler = "clang" %}
{% set compiler_version = "17" %}

[settings]
compiler={{ compiler }}
compiler.cppstd=20
# TODO set following to libc++ once all our dependencies are in conan
compiler.libcxx={{ detect_api.detect_libcxx(compiler, compiler_version) }}
compiler.version={{ compiler_version }}
```

But `conan profile show -pr:a RelWithDebInfo` says
```
ERROR: Error reading 'RelWithDebInfo' profile: Error parsing the profile text file: 
```

Note that there is no output after the final `:`

If I manually specify a value, it works.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide
