### ISSUE TITLE
[question] issue in updating boost library on jfrog artifactory with multiple profiles

### ISSUE THREAD

**Issue by manuelpagliuca** [conan-io/conan#15617]
### What is your question?

Hi I would like to know how can I update a packag (to the latest version) that I've on JFrog Artifactory remote.

For various reasons at the moment I'm using 1.60.2 (and I can't update it right now, it will be a future operation).

I'm using the following conan profiles:

**Windows - AC25**
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.toolset=v142
compiler.cppstd=17
build_type=MinSizeRel
cmake:build_type=Release
ninja:build_type=Release
[options]
*:archicad=25
[build_requires]
[env]
```
**Windows - AC26**
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.toolset=v142
compiler.cppstd=17
build_type=MinSizeRel
cmake:build_type=Release
ninja:build_type=Release
[options]
*:archicad=26
[build_requires]
[env]
```
**MacOS**
```
[settings]
os=Macos
os.version=10.13
archicad_adk:os.version=None
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=14.0
compiler.libcxx=libc++
compiler.cppstd=17
build_type=MinSizeRel
cmake:build_type=Release
ninja:build_type=Release
openssl:build_type=Release
[options]
[build_requires]
[env]
MACOSX_DEPLOYMENT_TARGET=10.13
```
Actually there are others for the debugging builds.

I would like to update the current `boost/1.77.0@` to `boost/1.83.0@` (or 1.83.0), this is how it is displayed on Artifactory:
<img width="467" alt="image" src="https://github.com/conan-io/conan/assets/1337959/64b39f94-d266-4dc4-a8bb-010a2662fe51">
I think the three packages are related to the three configurations that I've pasted there.

My attempt in updating the boost library was the following:
1. Download the [latest boost version](https://conan.io/center/recipes/boost) from conan center and installing it through the `conanfile.txt`, I didn't use the option `-pr` for installing using one of the three profiles (`win_ac25`,  `win_ac26`, `macos`). On the remote macos machine I'm using I can't any profile, it prompt an error.
2. Upload the installed boost package on the remote through the command `conan upload ... -r REMOTE`
3. Updating the `conanfile.py` with the new version of boost `1.83.0`.
4. Committing the changes will trigger a GitHub workflow.

The workflow prompt me an error during a particular step:
```
User of remote 'jfrog' is already 'github'
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=MinSizeRel
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.toolset=v142
compiler.version=16
os=Windows
os_build=Windows
cmake:build_type=Release
ninja:build_type=Release
[options]
*:archicad=26
[build_requires]
[env]

boost/1.83.0: Not found in local cache, looking in remotes...
boost/1.83.0: Trying with 'jfrog'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.83.0: Downloaded recipe revision 0
ERROR: boost/1.83.0: Cannot load recipe.
Error loading conanfile at 'C:\Users\runneradmin\.conan\data\boost\1.83.0\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\runneradmin\.conan\data\boost\1.83.0\_\_\export\conanfile.py
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\runneradmin\.conan\data\boost\1.83.0\_\_\export\conanfile.py", line 2, in <module>
    from conan.errors import ConanException, ConanInvalidConfiguration
ModuleNotFoundError: No module named 'conan.errors'
```
The step is compost by the following commands:
```
dir
  mkdir build_Browser
  dir
  md build-26
  cd build-2[6](https://github.com/jfrog-Group/BIM-ArchiCAD-Plugin/actions/runs/7800048986/job/21272087406#step:13:6)
  conan config install ..\conan\config
  conan user github --remote jfrog --password "***"
  conan install .. --profile win_ac26 --settings build_type=MinSizeRel
  cd ..
  cd build_Browser
  conan install .. --profile cef_release --settings build_type=Release
  cd ..
```

I'm sure that I'm making some big mistake, but I have lot of confusion on what I should do for uploading the correct binaries. I can confirm that by comparing the two directories on jfrog, I see that they are disposed in two different manners.
<img width="466" alt="image" src="https://github.com/conan-io/conan/assets/1337959/64c992a6-c8ec-42be-828d-55fdb4904704">

Can anyone help me solve this puzzle? Because I will need to do this operation a couple of time before passing to Conan 2.

Thank you in advance!

**Comment by memsharded** [comment]
Hi @manuelpagliuca 

Thanks for your question.

It seems you are using an older version of Conan.
Please update to the latest Conan 1.62
Read from https://docs.conan.io/1/introduction.html#stable

> This means that public repositories, like ConanCenter, assume the use of the latest version of the Conan client, and using an older version may result in failure of packages and recipes created with a newer version of the client.

Then, there are a couple of very important things you need to do as soon as possible:

- it seems you are not using revisions yet. This has been recommended for a few years now. Check
   - https://docs.conan.io/1/versioning/revisions.html#package-revisions
   - https://docs.conan.io/1/versioning/introduction.html#package-revisions
   - https://docs.conan.io/1/howtos/using_rrev_and_lockfiles.html#recipe-revisions
- it seems you are still using the single-profile approach with ``os_build`` and ``arch_build`` defined. The new approach, using 2 profiles and dropping those settings has also been recommended for some years .Check for example https://docs.conan.io/1/systems_cross_building/cross_building.html#cross-building-with-conan

**Comment by manuelpagliuca** [comment]
HI @memsharded, first of all thanks for answering.

What do you mean to the latest Conan 1.62? I'm currently using the 1.62.0, and by checking conan changelogs I see that there are no other updates.

The newer version is the Conan 2.0 (now 2.0.17), I think you are referring to that (right?).

So without using Conan 2.0, I can't use conan-center, this is interesting, so if I would like to update the conan recipe I should use the source files and build the binaries from that?

The project on which I'm working on is set with this version and without revisioning, it is explicitily disabling the revisioning.

Part of the README.md: 
> Build the add-on
> IMPORTANT
> 
> Creating a build directory outside of the source tree is expected.
> Set revisions_enabled to 0 in conan.conf under the general section or execute.
> Currently the ADK packages are built without revisions.

I'm going to check the examples, anyway if the conversion to conan 2.0 is mandatory for doing this operation, how complex is the migration to the newer version?

The project has many packages, one ADK to be built, and multiple workflows that are using conan.

Sorry if I impose some resistance on this issue, but it actually involves a lot of changes and I would like to resolve it at a later time.

Obviously if it is no longer difficult to update the boost library on the current obsolete version.

**Comment by memsharded** [comment]
> What do you mean to the latest Conan 1.62? I'm currently using the 1.62.0, and by checking conan changelogs I see that there are no other updates.

yes, Conan 1.62 should work with ConanCenter

> The newer version is the Conan 2.0 (now 2.0.17), I think you are referring to that (right?).

> So without using Conan 2.0, I can't use conan-center, this is interesting, so if I would like to update the conan recipe I should use the source files and build the binaries from that?

No, we keep running CI and testing everything with Conan 1.62, this should work. I think it could be something else.


The first thing I would try is to re-install Conan. It could be there is something corrupted in your Conan installation, can you please try that and let me know?


> Set revisions_enabled to 0 in conan.conf under the general section or execute.
Currently the ADK packages are built without revisions.

I am afraid this looks very legacy, like 4-5 years old advice

> Sorry if I impose some resistance on this issue, but it actually involves a lot of changes and I would like to resolve it at a later time.

Sure, no prob 🙂 
The issue is that Conan 2.0 has been out for 1 year, it was in beta for 2.5 years now. Revisions have been there for around 5 years... And now we are approaching the end of updates of Conan 1.X, in ConanCenter. Not that it will be breaking, but it will stop getting updates in the close future. The idea is that those changes could have been done slowly in that ADK project (is it public, do you have link?) in the last 3 years, and now it might be a bit of a rush, the "later" cannot be that later, because what you are trying to do, to update to a recent boost will no longer be possible unless using Conan 2.0 in the following months, because ConanCenter will only get new future boost versions for Conan 2.0

**Comment by manuelpagliuca** [comment]
I think there is nothing wrong in the installation of conan, I'm using a virtual environment both on the local that on the workflow.

**Comment by manuelpagliuca** [comment]
At the moment I have only to update to the newer boost library, if this works I will try to build the ADK (isn't public but I found this on [conan-center](https://conan.io/center/recipes/archicad-apidevkit?version=26)).

**Comment by memsharded** [comment]
This is the line that I am confused about:

> from conan.errors import ConanException, ConanInvalidConfiguration
ModuleNotFoundError: No module named 'conan.errors'

This can only mean that the Conan installation is missing the ``conan/errors.py`` file in the installed Conan folder.
If I go to my virtualenv, I can see the file in ``C:\Users\memsharded\Envs\conanpip36\Lib\site-packages\conan\errors.py`` for my Conan 1.62 installation. Can you please double check if that file is in your installation?

**Comment by manuelpagliuca** [comment]
I sadly can't check it, because that are the logs from GH runner, if there is a command that can print out the file I can run that.

But I can't directly access that file sadly.

---
Edit1:

I checked the errors.py that I've on the venv on my local machine and I got this:

```python
from conans.errors import ConanException
from conans.errors import ConanInvalidConfiguration
from conans.errors import ConanInvalidSystemRequirements
```

**Comment by memsharded** [comment]
> I checked the errors.py that I've on the venv on my local machine and I got this:

This looks good. Does the error also happens the same if you run in your local machine and not in GH actions

> I sadly can't check it, because that are the logs from GH runner, if there is a command that can print out the file I can run that.

You can run any command in Github actions? Like listing the <virtualenv>/Lib/site-packages/conan contents with a ``ls`` or ``dir`` in Windows or similar?

Maybe the GIthub action cache is corrupted after some Conan version updates, it might make sense to guarantee that the Github action starts fresh?

**Comment by manuelpagliuca** [comment]
I can use a new caching key for that, so we can try it from scratch if this works.

Yes I can run any Unix command on the GH Actions, which files you need to check? (and plesae tell me if before or after the conan install).

**Comment by manuelpagliuca** [comment]
This is the build workflow for creating a WindowsInstaller, `Configure conan and install dependencies for plugin and browser` is the interested one (let me know if you want me to resize the code only to that action).

```yaml
name: Build Archicad Windows Installer for commits and pull requests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: MinSizeRel
  CONAN_REVISIONS_ENABLED: 0
  JfrogPlannerSuiteVersion: 0.0.0.0
  SONAR_SCANNER_VERSION: 5.0.1.3006
  SONAR_SERVER_URL: "https://sonarcloud.io"

jobs:
  snyk:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    name: Snyk Scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Snyk Setup
        if: ${{ ! cancelled() }}
        uses: snyk/actions/setup@master

      - name: Run snyk test
        if: ${{ ! cancelled() }}
        uses: Jfrog-Group/bim-github-actions/snyk-scan@main
        with:
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          snyk_org_id: ${{ vars.SNYK_ORG_ID }}
          snyk_command: test
          snyk_args: ${{ vars.SNYK_TEST_ARGS }}
          snyk_continue_on_error: true

      - name: Run snyk code test
        if: ${{ ! cancelled() }}
        uses: Jfrog-Group/bim-github-actions/snyk-scan@main
        with:
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          snyk_org_id: ${{ vars.SNYK_ORG_ID }}
          snyk_command: code test
          snyk_args: ${{ vars.SNYK_CODE_TEST_ARGS }}
          snyk_continue_on_error: true

  WindowsBuild:
    needs: ["snyk"]
    runs-on: ["windows-2019"]

    env:
      AZURE_CREDENTIALS: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      SUBSCRIPTION: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      AZ_CLI_VERSION: 2.25.0
      JfrogPlannerSuiteVersion: 0.0.0.0

    strategy:
      matrix:
        adk: [26, 25]

    defaults:
      run:
        shell: cmd

    steps:
    # Windows Plugin
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          path: translations
          ref: translations

      - uses: microsoft/setup-msbuild@v1.3.2

      - name: Cache python packages
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-ac26-2

      - name: Cache conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan
          key: ${{ runner.os }}-ac26-6-${{ hashFiles('conanfile.py', 'conan/config/profile/win*')}}
          restore-keys: |
            ${{ runner.os }}-ac26-6-

      - name: Install conan
        run: pip install --upgrade "conan<1.44"

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: corretto

      - name: Cache SonarCloud packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Download and set up sonar-scanner
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-windows.zip
        shell: pwsh
        run: |
          New-Item -Force -ItemType directory -Path $HOME\.sonar
          curl -sSLo $HOME\.sonar\sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }}
          unzip -o $HOME\.sonar\sonar-scanner.zip -d $HOME\.sonar\
          echo "$HOME\.sonar\sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-windows\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Download and set up build-wrapper
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-win-x86.zip
        shell: pwsh
        run: |
          curl -sSLo $HOME\.sonar\build-wrapper.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME\.sonar\build-wrapper.zip -d $HOME\.sonar\
          echo "$HOME\.sonar\build-wrapper-win-x86" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Configure conan and install dependencies for plugin and browser
        run: |
          dir
          mkdir build_Browser
          dir
          md build-${{ matrix.adk }}
          cd build-${{ matrix.adk }}
          conan config install ..\conan\config
          conan user github --remote jfrog --password "${{ secrets.CONAN_TOKEN_BIMPLUGIN_GITHUB }}"
          conan install .. --profile win_ac${{ matrix.adk }} --settings build_type=${{ env.BUILD_TYPE }}
          cd ..
          cd build_Browser
          conan install .. --profile cef_release --settings build_type=Release
          cd ..

      - name: Extract and prepare Chromium Embedded Framework
        run: |
          7z x -o"Browser\cef" Browser\cef_binary_*.7z.001
          rmdir Browser\cef\tests\cefsimple
          xcopy /S /V /Y Browser\cefsimple Browser\cef\tests\cefsimple

      - name: Build browser
        run: |
          cmake -S Browser\cef -B build_Browser -A x64
          msbuild build_Browser\cef.sln -target:cefsimple -p:Configuration=Release
          mkdir build-${{ matrix.adk }}\cef\
          dir
          dir build-${{ matrix.adk }}\
          xcopy /S /V /Y build_Browser\tests\cefsimple\Release\* build-${{ matrix.adk }}\cef\

      - uses: azure/login@v1.6.1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Get Certificate for Signing
        run: |
          az keyvault secret download --file Installer\Setup\Documents\cert.pfx --encoding base64 --name ct-ev-revit-csr --subscription ${{ env.SUBSCRIPTION }} --vault-name kv-ct-shared-ev-hsm

      - name: Sign browser executable
        run: |
          "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe" sign /f Installer\Setup\Documents\cert.pfx /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 build_Browser\tests\cefsimple\Release\cefsimple.exe

      - name: Build plugin and scan with SonarCube x64 wrapper
        run: |
          cd build-${{ matrix.adk }}
          mkdir ..\sonar-results
          build-wrapper-win-x86-64.exe --out-dir ..\sonar-results conan build ..
          xcopy /S /V /Y ..\translations\windows\* .

      - name: Sonar scan
        working-directory: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: matrix.adk == '26'
        run: |
          sonar-scanner --define sonar.cfamily.build-wrapper-output=sonar-results

      - name: Moving source files for the Windows Installer
        run: |
          mkdir plugin
          cp ./build-${{ matrix.adk }}/JfrogPlannerSuite.apx ./plugin
          cp ./build-${{ matrix.adk }}/Updater.exe ./plugin
          cp -r ./build-${{ matrix.adk }}/cef ./plugin
          cp -r ./build-${{ matrix.adk }}/de-DE/ ./plugin
          cp -r ./build-${{ matrix.adk }}/de-AT/ ./plugin
          cp -r ./build-${{ matrix.adk }}/en/ ./plugin
          cp -r ./build-${{ matrix.adk }}/en-US/ ./plugin
          cp -r ./build-${{ matrix.adk }}/es-ES/ ./plugin
          cp -r ./build-${{ matrix.adk }}/fr-FR/ ./plugin
          cp -r ./build-${{ matrix.adk }}/it-IT/ ./plugin
          cp -r ./build-${{ matrix.adk }}/nl-NL/ ./plugin
          cp -r ./build-${{ matrix.adk }}/pl-PL/ ./plugin
          cp -r ./build-${{ matrix.adk }}/pt-PT/ ./plugin
          cp -r ./build-${{ matrix.adk }}/tr-TR/ ./plugin
          cp -r ./build-${{ matrix.adk }}/ru-RU/ ./plugin
          cp -r ./build-${{ matrix.adk }}/cs-CZ/ ./plugin

    # Windows Installer
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 5.0.x

      - name: restore nuget packages
        run: nuget restore Installer/Installer.sln

      - name: Build Installer
        run: msbuild /p:Configuration="Release (A${{ matrix.adk }})" /p:Platform=x64 Installer/Installer.sln

      - name: Delete Certificate
        if: ${{ always() }}
        run: |
          del Installer\Setup\Documents\cert.pfx

      #workaround for version number, until it is available from the plugin build part.
      - name: Create changelog files
        id: create-2022-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "Changelog-en-${{ env.JfrogPlannerSuiteVersion }}.json"
          json: '{"about":"${{ github.event.release.name }}", "description":"-", "newFeatures":"-"}'
          dir: 'Installer/Setup/bin/Release (A${{ matrix.adk }})/'

      - name: Rename .msi - file with version
        run: |
          mv "Installer/Setup/bin/Release (A${{ matrix.adk }})/Setup-1.0.0.0.msi" "Installer/Setup/bin/Release (A${{ matrix.adk }})/Setup-${{ env.JfrogPlannerSuiteVersion }}.msi"
          mv "Installer/Setup/bin/Release (A${{ matrix.adk }})/Setup-1.0.0.0.wixpdb" "Installer/Setup/bin/Release (A${{ matrix.adk }})/Setup-${{ env.JfrogPlannerSuiteVersion }}.wixpdb"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Installer Package (A${{ matrix.adk }})
          path: Installer\Setup\bin\**
    environment: C++
```

**Comment by memsharded** [comment]
```
- name: Cache conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan
          key: ${{ runner.os }}-ac26-6-${{ hashFiles('conanfile.py', 'conan/config/profile/win*')}}
          restore-keys: |
            ${{ runner.os }}-ac26-6-

      - name: Install conan
        run: pip install --upgrade "conan<1.44"
```

It seems the GH action is forcing an older Conan, not 1.62. Please make sure to change that before proceeding.

This is probably the problem?

Then, yes, after the ``pip install``, at that moment you can check the files in your ``virtualenv`` (I don't know where the GH has is Python environment folder, sorry). 

As a recommendation, running a simple ``conan --version`` after the installation, so the logs Contain the actual version being used in production is very useful.

**Comment by manuelpagliuca** [comment]
> It seems the GH action is forcing an older Conan, not 1.62. Please make sure to change that before proceeding.

Do you mean to change the caching key?

---

Edit 1:

Something like that shouldn't give any issues (I changed the caching key and added a print for checking the conan version).

```yaml
      - name: Cache python packages
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-ac26-2024-${{ hashFiles('conanfile.py', 'conan/config/profile/win*')}}

      - name: Cache conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan
          key: ${{ runner.os }}-ac26-2024-${{ hashFiles('conanfile.py', 'conan/config/profile/win*')}}
          restore-keys: |
            ${{ runner.os }}-ac26-2024-

      - name: Install conan
        run: |
          pip install --upgrade "conan<1.44"
          conan --version
```
