### ISSUE TITLE
[question] are custom compiler settings used for ABI compatibility with requirements?

### ISSUE THREAD

**Issue by hoyhoy** [conan-io/conan#15631]
### What is your question?

I have various sanitizer settings in my settings.yml, but conan 2.0.17 is pulling the wrong binaries in at link time.  Do I have to manually add the custom settings to compatibility or package_id?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
If they are first level settings, ``settings = "os", "arch", ... "mysetting"``. If not they are automatically added, just define their values in the profiles and ``package_id`` should include them.

**Comment by hoyhoy** [comment]
Do I need to add `undefined_behavior_sanitizer` and so on to my `settings` array or append them to the `package_id` criteria manually?

```
compiler:
    gcc:
        version: [...]
        ...
        address_sanitizer: [null, True]
        hwaddress_sanitizer: [null, True]
        kernel_address_sanitizer: [null, True]
        thread_sanitizer: [null, True]
        undefined_behavior_sanitizer: [null, True]
        pointer_compare_sanitizer: [null, True] # only valid with address or kernel_address
        pointer_subtract_sanitizer: [null, True] # only valid with address or kernel_address
        shadow_call_stack_sanitizer: [null, True]
        leak_sanitizer: [null, True]
        stack_protector: [null, True]
        stack_check: [null, True]
```

I assumed (wrongly) that including `"compiler"` in my `conanfile.py`'s `settings` array would work.  I just switched between `thread` and `undefined_behavior_sanitizer` today, but my `openssl` didn't change package_ids and the `undefinied_behavior` package linked against the `thread`-instrumented binaries.
