### ISSUE TITLE
[question] deploy() in conanfile.py

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/conan#15729]
### What is your question?

Hi!

The question is how can I get dependencies from cache in my current project with deploy() method from conanfile.py?

When I try to run conan install command with `--deployer-package=*` argument, I get this error:
line 272, in deploy
  File "<frozen ntpath>", line 108, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

ERROR: expected str, bytes or os.PathLike object, not NoneType

I tried to use the syntax from documentation:
```
def deploy(self):
        copy(self, "*", src=self.package_folder, dst=self.deploy_folder)
```
`self.package_folder` - what represents? Is it the root for conan dependencies?
What I understood, self.package_folder will take binary artifacts from artifactory server, not from my dependencies.
But I would like to get dependencies from my cache.
        
Thank you!

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

Thanks for your question

> What I understood, self.package_folder will take binary artifacts from artifactory server, not from my dependencies.

No, the ``self.package_folder`` is always a local folder to the cache, to a package that has already been downloaded and installed in the cache. 

The syntax is intended to be used as ``conan install --requires=mypkg/1.0 --deployer-package="*"``, is this the use case? Maybe you can share a ``conanfile`` and the exact command to reproduce this? (at the very least, it is a UX bug, that kind of trace shouldn't happen, so we might want to improve the error message)

**Comment by Vasile-Creuco** [comment]
This is the deploy() method from my `conanfile`:
```
def deploy(self):
    _build_type = self.build_type
    if 'package_destinations' in self.conan_data:
        pkgDestinations = self.conan_data['package_destinations']
        if _build_type in pkgDestinations:
            deployData = pkgDestinations[_build_type]
        else:
            deployData = pkgDestinations['default']
            
    # Iterate through the imports
    for dImport in deployData:
      # Import / Copy files from conan cache to workspace
      folderA = os.path.join(self.package_folder, dImport['source'])
      print(f"src folder: {folderA}")
      folderB = os.path.join('.', dImport['target'])
      print(f"dst folder: {folderB}\n")
      # def copy(conanfile, pattern, src, dst, keep_path=True, excludes=None, ignore_case=True):
      copy(self, pattern=dImport['pattern'], src=folderA, dst=folderB, keep_path=True, excludes=("conan*.txt", "conan*.bat", "conan*.sh"))
```
I'm also using `conadata.yml` to get requirements:

```

requires: []
# package dependency requirements for tools
tool_requires: []
# package dependency requirements only for package testing
test_requires: []
# package dependency requirements only to build
build_requires: [name/1.x.x@user/channel]

package_destinations:
  default:
  - pattern: '*.*'
    source: .
    target: ../../rootfolder
  development:
  - pattern: '*.*'
    source: .
    target: ../../rootfolder
```
