### ISSUE TITLE
Conan CLI: Add option to conan remove to just skip without error if package does not exist

### ISSUE THREAD

**Issue by vincesp** [conan-io/conan#16221]
The `conan remove` command is missing an option to skip without returning an error if the package to be removed does not exist.

Background: It is really cumbersome to build an Azure pipeline that detects if a package exists and only runs the `conan remove` task if it does. If using a pool with numerous agents, we cannot be sure in which state the conan cache on every single agent is, so we need to clean the cache just to be sure. Adding `continueOnError: true` to the task only helps partially, as the pipeline run will show "completed with warnings" which does not reflect the actual outcome properly.

**Comment by memsharded** [comment]
Hi @vincesp 

This doesn't look like a docs issue, but a client one. Moving it to the Conan client repo.

**Comment by memsharded** [comment]
> The conan remove command is missing an option to skip without returning an error if the package to be removed does not exist.

```bash
$ conan remove zlib/1.4
Remove summary:
Local Cache
```

This works without failing, not sure what you mean (zlib/1.4 doesn't exist yet)


> Background: It is really cumbersome to build an Azure pipeline that detects if a package exists and only runs the conan remove task if it does. If using a pool with numerous agents, we cannot be sure in which state the conan cache on every single agent is, so we need to clean the cache just to be sure. 

It is not clear the background. Why would you remove a package if it exists? The whole purpose of using Conan is not having to rebuild something that already exists, this flow shouldn't be necessary in the first place.

**Comment by memsharded** [comment]
Hi @vincesp 

Any further feedback here?

**Comment by vincesp** [comment]
@memsharded 

In a build pipeline, we want to clean certain package to force their rebuild. But we don't want to empty the local cache completely, as this would defeat the purpose of a cache.

As we have many agents in our pool, we cannot be sure which packages have been built on which agent before.

**Comment by memsharded** [comment]
> In a build pipeline, we want to clean certain package to force their rebuild. But we don't want to empty the local cache completely, as this would defeat the purpose of a cache.

But rebuilding a package that exists in the server is considered a pipeline or model error. Anything that produces a new ``package revision`` for an existing ``recipe revision`` + ``package_id`` is a model error and leaves the door open for problems in traceability and reproducibility. Conan packages should only be built when there are changes in the original sources/recipe (captured in the ``recipe-revision``), or when there are changes in the configuration (settings, options or dependencies changing, captured in the ``package_id``). Conan will automatically build only what is strictly necessary, having to empty the local cache from certain packages to force a re-build sounds against the recommended practices.


It is also not clear what is the error:
```
λ conan remove potato/1.0
Remove summary:
Local Cache
```
works well, it doesn't fail, even if ``potato/1.0`` doesn't exist in the cache.

**Comment by vincesp** [comment]
```shell
PS> conan --version     
Conan version 2.4.1
PS> conan remove -c zlib
ERROR: Recipe 'zlib' not found
PS> echo $LASTEXITCODE
1
```

So in our pipelines, we have the following code:
```yaml
- script: conan remove -c ${{ parameters.packageName }} || true
  displayName: Conan Remove ${{ parameters.packageName }} (POSIX)
  condition: or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))

- script: conan remove -c ${{ parameters.packageName }} || exit /b 0
  displayName: Conan Remove ${{ parameters.packageName }} (Windows)
  condition: eq(variables['Agent.OS'], 'Windows_NT')
```

**Comment by memsharded** [comment]
Ok, I see what you mean.

I think this is due to some legacy behavior that couldn't be fully removed in Conan 2, when using just a package name.

The recommended approach for this is using patterns:
```
conan remove "zlib/*" -c
```
will achieve the behavior that you want, that is, remove all ``zlib`` versions, but not erroring if it doesn't exist. Can you please try that and let me know?

**Comment by vincesp** [comment]
It seems to work.

**Comment by memsharded** [comment]
Ok, great, thanks for the feedback.

I have checked the docs, and I cannot find occurrences of this, but the ``conan remove "zlib/*"`` syntax is used, for example in https://docs.conan.io/2/reference/commands/remove.html.

I have also checked the code and the use cases. There might be users relying on this as a feature, for example if doing an operation (upload, remove) after some package has been created, so it is guaranteed to be there, and if it is not there, they are happy to get an error. So most likely it is not worth the risk to try to change this behavior and make it not raise an error for the usage without a pattern ``*``.

I am closing this as solved, no option is necessary as the pattern syntax achieve that, but please re-open or create new tickets for any further question or issue. Thanks for the feedback!

**Comment by vincesp** [comment]
Update:

Even `conan remove -c "*"` does not cleanup the local cache completely.

In order for our pipelines to use the information from Artifactory, not from previous (potentially failed) local build attempts, we had to add the following to our pipelines:

```yaml
- script: |
    rm -rf $HOME/.conan2/p
    rm $HOME/.conan2/.conan.db
  displayName: Clean Conan cache (POSIX)
  condition: or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))

- script: |
    rmdir /s /q %USERPROFILE%\.conan2\p
    del %USERPROFILE%\.conan2\.conan.db
  displayName: Clean Conan cache (Windows_NT)
  condition: eq(variables['Agent.OS'], 'Windows_NT')
```
