### ISSUE TITLE
clang 18 missing in default setting profile for conan 1.64.1

### ISSUE THREAD

**Issue by pgeler** [conan-io/conan#16263]
### What is your suggestion?

with ubuntu 24.04 default clang version is 18, just updating setting.yml

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @pgeler 

Thanks for the feedback.

Yes, Conan 2 already has it:
```yaml
clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0",
                  "5.0", "6.0", "7.0", "7.1",
                  "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18"]
```

Conan 1 might update the ``settings.yml`` but the truth is that releases for Conan 1 are much slower nowadays, if you need it, the best would be to add it to your ``settings.yml`` and manage it with ``conan config install``
