### ISSUE TITLE
[question] how to see inferred package_type based on options?

### ISSUE THREAD

**Issue by wuziq** [conan-io/conan#16265]
### What is your question?

My conanfile.py:

```
class Foo(ConanFile):
    ...
    options = {
        "shared": [True, False],
    }

    default_options = {
        "shared": True
    }
    ...
```

Then I run `conan inspect .` and I see:

```
...
options:
    shared: True
options_definitions:
    shared: ['True', 'False']
package_type: None
...
```

However, I thought that Conan should infer the `package_type` to be `shared-library`, based on the `shared` option.  Is that correct?

Maybe `conan inspect` simply shows what is strictly in the conanfile.py.  If so, is there a way to see what `package_type` Conan has inferred from the options?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide
