### ISSUE TITLE
[question] Conan with CMake failing only in CI pipeline but not on local machine.

### ISSUE THREAD

**Issue by NateSeymour** [conan-io/conan#16497]
### What is your question?

Hi! Thank you for taking the time to help me here. 

I am experiencing a strange bug with `conan` (I believe, but could possible be do to other components) in my GitHub CI pipeline. For reference, [here is the repo](https://github.com/NateSeymour/unlogic) and [a failed build](https://github.com/NateSeymour/unlogic/actions/runs/9574310975/job/26397328962).

[Here is the relevant snippet](https://github.com/NateSeymour/unlogic/blob/main/.github/workflows/unlogic-ci.yml#L18) (line 18ff) from my `ci.yml`:

```yaml
    - name: Install Conan
      run: wget https://github.com/conan-io/conan/releases/download/2.2.2/conan-2.2.2-amd64.deb && sudo dpkg -i conan-2.2.2-amd64.deb
    - name: Configure Conan
      run: conan profile detect
    - uses: actions/checkout@v4
    - name: Configure Project and Install Conan Dependencies
      run: mkdir cmake-build-release && sudo conan install . --output-folder="cmake-build-release" --build=missing -s build_type="Release" -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
    - name: Configure Project
      run: cd cmake-build-release && cmake .. --preset conan-release -G "Ninja"
```

The "Configure Project" command is the one that is failing with the following error message:

```
CMake Error at cmake-build-release/cmakedeps_macros.cmake:67 (message):
  Library 'sfml-audio-s' not found in package.  If 'sfml-audio-s' is a system
  library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  cmake-build-release/SFML-Target-release.cmake:23 (conan_package_library_targets)
  cmake-build-release/SFMLTargets.cmake:24 (include)
  cmake-build-release/SFMLConfig.cmake:16 (include)
  CMakeLists.txt:7 (find_package)
```

Which is strange, because the build succeeds when running the same commands on my Ubuntu 23.10 development computer and also on MacOS 13. 

I've tried the latest conan `2.4.1` on the CI as well, but downgraded it to match the one on my local machine (`2.2.2`) to eliminate that potential source of error.

Any help/advice/direction would be greatly appreciated! This one really has me scratching my head. Thanks for all the work you do!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide
