### ISSUE TITLE
[feature] Remote receipes in local-recipes-index

### ISSUE THREAD

**Issue by raplonu** [conan-io/conan#16641]
### What is your suggestion?

Hi, I'm experimenting with the 'local-recipes-index' features added in conan 2.2.

Conan index is made for register non conan project. To reference a new recipe, we have to write a 'conanfile.py'.

However, when we want to reference a project that already have a 'conanfile.py', AFAIK, the only solution is to copy the file and adds a `source` method (among other things). This requires to maintain the same file (with some differences) at two different locations.

IMHO, moving the `conanfile.py` from the project to the index is not a solution. `conanfile.py` in project folder is extremely useful when developing: editable package, cmake preset, etc.

A solution I have in mind is to have a more rich schema in `config.yml`. Instead of just listing `conanfile.py` in folders, we could also reference them with a "git" or "url".

```yml
versions:
    "1.0.0":
        git: "https://github.com/myself/myproject.git"
        tag: "1.0.0"
    "1.1.0":
        url: "https://myself.com/myproject_1.1.0.tar.gz"
        sha256: "6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e"
```

This way, conan would use the `conanfile.py` from a remote location.

Optional arguments could also specify 'conanfile.py' location in the cloned folder other than root or maybe the commit hash.

One last argument in favor of that is that would allow to have a perfect symmetry between the index and a conan server. As of today, my server have both recipes from the index and other conan projects. If it dies, I have to re-upload recipes from the index (easy) and from all of my conan projects (requiring to checkout and export all tags, etc.).

What do you think ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide
