### ISSUE TITLE
[bug] apply_conandata_patches: Massive patch fail to apply with "No such file or directory"

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [conan-io/conan#16727]
### Describe the bug

OS:  Debian GNU/Linux 12 (bookworm) on Windows 10 x86_64
Conan version 2.5.0

while trying to apply a massive 30MB patch i got the following error:
```
ERROR: freeimage/3.18.0: Error in source() method, line 16
        apply_conandata_patches(self)
        FileNotFoundError: [Errno 2] No such file or directory: '/home/builder/.conan2/p/freei738e6c6a78aec/s/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Program.cs"'
```
the file `'/home/builder/.conan2/p/freei738e6c6a78aec/s/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Program.cs'` does exists but it seems that during the parsing the last `"` wasn't removed. meaning that the file searched was `Program.cs"` instead of `Program.cs`

### Workaround

```
	def source(self):
		get(self, **self.conan_data["sources"][self.version])
		for patch in self.conan_data["patches"][self.version]:
			file = patch["patch_file"]
			strip = patch["strip"] or 0
			self.run(f"patch --strip={strip} < {file}", cwd=self.source_folder)

```

### How to reproduce it

Conandata:
```
sources:
  "3.18.0":
    url: "http://downloads.sourceforge.net/freeimage/FreeImage3180.zip"
    sha256: "f41379682f9ada94ea7b34fe86bf9ee00935a3147be41b6569c9605a53e438fd"
    strip_root: true

patches:
  "3.18.0":
    - patch_file: "patches/cmake.patch"
      strip: 1
      patch_description: Full modern build refactoring, with every external libraries optional
```

source section
```
	def source(self):
		get(self, **self.conan_data["sources"][self.version])
		apply_conandata_patches(self)
```

compressed patch file.
[cmake.patch.zip](https://github.com/user-attachments/files/16373755/cmake.patch.zip)
