### ISSUE TITLE
[bug] Changing info.settings.compiler erases other compiler options

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16731]
### Describe the bug

OS: Windows, Compiler. VS 2019, Conan: 1.64.1

Hi,

I have a problem how changing self.info.settings.compiler affects the other compiler relevant members that might already be set.

Image this (this is actually the msvc_compatible function in info.py):

        compatible = self.clone()
        # Assume compatible.settings.compiler.cppstd is set
        compatible.settings.compiler = "Visual Studio" # This clears every compiler.* so I lose "cppstd"

This means that when this compatibility package is added binary packages where cppstd is being set, will not be found.
(meaning binary compatibility between 'msvc' and 'Visual Studio' appears to be broken - at least this is what I see)
What do I miss?
Thanks,

### How to reproduce it

* Create a 'Visual Studio' package with a profile where cppstd is set (to 17 for example)
* Switch to 'msvc' and try to pick up the previously compiled binary package, it doesn't seem to be working

**Comment by memsharded** [comment]
Hi @harsszegi 

The ``settings`` structure is hierarchical. The ``compiler.xxxx`` sub-settings belong to specific values of the ``compiler``, see:

```yaml
compiler:
    gcc:
        version: ["4.1", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9",
                    "14", "14.1"]
        libcxx: [libstdc++, libstdc++11]
        threads: [null, posix, win32]  # Windows MinGW
        exception: [null, dwarf2, sjlj, seh]  # Windows MinGW
        cppstd: [null, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
        cstd: [null, 99, gnu99, 11, gnu11, 17, gnu17, 23, gnu23]
    msvc:
        version: [170, 180, 190, 191, 192, 193, 194]
        update: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        runtime: [static, dynamic]
        runtime_type: [Debug, Release]
        cppstd: [null, 14, 17, 20, 23]
        toolset: [null, v110_xp, v120_xp, v140_xp, v141_xp]
        cstd: [null, 11, 17]
```
Not all values have all subsettings, and the subsettings have different values too, even if the subsetting as ``compiler.version`` has the same name.
So when the root ``compiler=xxx`` is redefined, all the subsettings values are cleared, because keeping the previous ones doens't really make sense.

It is necessary to redefine them too.

As a side note, it is not really necessary to migrate to ``compiler=msvc`` in Conan 1. You can keep using ``compiler="Visual Studio"`` in Conan 1 and migrate to ``compiler=msvc`` in Conan 2, as configuration files such as profiles are expected to be different anyway in Conan 1 and Conan2, so the expectation is to manage them with different ``conan config install`` repos.
