### ISSUE TITLE
[question] Help with Installing zlib using Conan 2.7.0 Python API

### ISSUE THREAD

**Issue by omayma-el** [conan-io/conan#17122]
### What is your question?

Hi everyone,

I'm trying to install zlib/1.2.13 using the **Conan 2.7.0 Python API**, but I'm running into issues where the binaries are not being downloaded, and I only get a **conandata.yml** file in the cache.

## Here is the Python code I am using:

```
from conan.api.conan_api import ConanAPI
from conan.api.model import Remote, RecipeReference

conan = ConanAPI()

remote = Remote(name="conancenter", url="https://center.conan.io", verify_ssl=False)

r = RecipeReference.loads("zlib/1.2.13")
ref = conan.list.latest_recipe_revision(r, remote=remote)
profile_host = conan.profiles.get_profile(["host"])
profile_build = conan.profiles.get_profile(["build"])

deps_graph = conan.graph.load_graph_requires([ref], remotes=[remote], update=True,
                         profile_host=profile_host, profile_build=profile_build, 
                              tool_requires=None, lockfile=None)
ret = conan.install.install_binaries(deps_graph, remotes=[remote])
```

When I run this, the output I see is as follows:

```
======== Computing dependency graph ========
zlib/1.2.13: Not found in local cache, looking in remotes...
zlib/1.2.13: Checking remote: conancenter
zlib/1.2.13: Downloaded recipe revision 4e74ebf1361fe6fb60326f473f276eb5
Node Downloaded
```

In my Conan cache, I only see a **conandata.ym**l file that contains this:
```
patches:
  1.2.13:
    - patch_description: separate static/shared builds, disable debug suffix, disable building examples
      patch_file: patches/1.2.13/0001-Fix-cmake.patch
      patch_type: conan
sources:
  1.2.13:
    sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
    url:
    - https://zlib.net/fossils/zlib-1.2.13.tar.gz
    - https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz
```

However, there are no binaries in the cache.

## Profile Information
Both my host profile and build profile contain the following settings:
```
[settings]
os=Windows
arch=x86_64
build_type=Release
compiler=msvc
compiler.version=193
compiler.runtime=dynamic
compiler.runtime_type=Release
```

## What I'm Trying to Achieve
I’m trying to install zlib/1.2.13 using the Conan Python API, expecting the binaries to be installed from ConanCenter, but instead, I'm only seeing the recipe and the conandata.yml file, with no binaries downloaded.

## Could anyone help me understand:

- What I might be doing wrong with the Python API?
- How can I ensure that the binaries are installed if available on ConanCenter?
- Am I missing a step, or do I need to modify my profiles or settings?

Any help would be greatly appreciated! I'm new to Conan and may be missing something obvious, so any pointers or advice would be super helpful.

Thank you in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide
