### ISSUE TITLE
Visual Studio Version Detection on Appveyor Broken?

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1732]
In my Appveyor recipe I have this: 
```
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
```
Conan should detect and use Visual Studio 2015 on this image, but it doesn't as shown in the log below: 
```
Auto detecting your dev setup to initialize the default profile (C:\Users\appveyor\.conan\profiles\default)
Found Visual Studio 9
Found Visual Studio 10
Found Visual Studio 11
Found Visual Studio 12
Found Visual Studio 14
Found Visual Studio 15
Found clang 4.0
Default settings
    os=Windows
    arch=x86_64
    compiler=Visual Studio
    compiler.version=15
    build_type=Release
```

As you can see, it defaults to using compiler.version 15, which is VS 2017. 

The commands it returns from `tools.vcvars_command` is therefor invalid:
```
build_command: set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\../../VC/Auxiliary/Build/vcvarsall.bat" x86 && devenv npcap-0.93\packetWin7\Dll\Project\Packet.sln /upgrade && msbuild npcap-0.93\packetWin7\Dll\Project\Packet.sln /p:Configuration="Release No NetMon and AirPcap" /p:Platform="x86"
```
Which produces a failing build, with error "The system cannot find the path specified."

Reference:
https://ci.appveyor.com/project/BinCrafters/conan-npcap-dll/build/1.0.32/job/tf8hb0nq3xevp10r#L213
https://github.com/bincrafters/conan-npcap-dll/blob/master/conanfile.py
