### ISSUE TITLE
[feature] Allow adding dependencies from git url

### ISSUE THREAD

**Issue by razaqq** [conan-io/conan#17651]
### What is your suggestion?

The current system of adding 3rd party packages from remotes is fine.
However when consuming first party packages there is a huge unnecessary complexity.
One has to either host their own artifactory or work with `local-recipes-index` in an extra repository.

My suggestion would be to allow adding dependencies directly from a git url, similar to how cargo does for rust.

Example `Cargo.toml`
```toml
[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
regex = { git = "https://github.com/rust-lang/regex.git", branch = "next" }
regex = { git = "https://github.com/rust-lang/regex.git", tag = "1.10.3" }
regex = { git = "https://github.com/rust-lang/regex.git", rev = "0c0990399270277832fbb5b91a1fa118e6f63dba" }
```

This would make consuming first party packages significantly easier.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide
