### ISSUE TITLE
[bug] docker runner doesn't work when conanfile is inside subfolder

### ISSUE THREAD

**Issue by aagor** [conan-io/conan#17746]
### Describe the bug

Environment details:
* OS: Linux
* Conan version: 2.12.1
* Conan profile: nothing special, use docker runner as described [here](https://docs.conan.io/2/examples/runners/docker/basic.html)
 
When using the docker runner, only the current directory get's mapped into the container.
This is not sufficient when the Conanfile is in a subfolder like in this example: [Declaring the layout when the Conanfile is inside a subfolder](https://docs.conan.io/2/examples/conanfile/layout/conanfile_in_subfolder.html#examples-conanfile-layout-conanfile-in-subfolder).
Conan then can't access the root folder, as it's not mapped into the container and therefore fails to access files, leading to a build fail.

### How to reproduce it

```
$ git clone https://github.com/conan-io/examples2.git
$ cd examples2/examples/conanfile/layout/conanfile_in_subfolder/conan
$ conan create .
> Build fails here
$ docker inspect conan-runner-docker |jq .[].HostConfig.Binds
```

`jq` output:
```json
[
  "/home/<username>/examples2/examples/conanfile/layout/conanfile_in_subfolder/conan:/root/conanrunner/conan:rw"
]
```

**Comment by perseoGI** [comment]
Hi @aagor thank you for your report! 
That is definitely a great catch!

We are improving the conan runners, I'll include a workaround for this issue in https://github.com/conan-io/conan/pull/17542
Stay tuned for incoming updates.
I'll inform here when this problem is addressed 

Happy coding 🐸

**Comment by perseoGI** [comment]
Greetings @aagor,

I've been discussing with the team and we are considering giving support to this specific case. 
The docker runner only mounts the directory where the `conanfile.py` file resides.
Mounting parent directories automatically is currently not supported.

But here is a quick workaround to address this issue:

1. Edit your docker profile adding a configfile key:
```
[runner]
type=docker
...
configfile=<absolute_path>/configfile.yml
```
2. Create a `configfile.yml` following the schema specified here: https://containers.dev/implementors/json_reference/
```yml
run:
    mounts:
        <absolute_path>/examples2/examples/conanfile/layout/conanfile_in_subfolder/:
            bind: /root/conanrunner/   # This is the mount folder inside the docker runner -> kind of internal to conan...
            mode: rw
```
3. Execute `conan create` again and this time should work. 

I hope it helps!
