### ISSUE TITLE
[bug]Creating a 64 bits and then a 32 bits package from different sources

### ISSUE THREAD

**Issue by NSIRI** [conan-io/conan#17792]
### Describe the bug

Hello,
I have written a recipe for jni (version 1.8.0_92) wich have differents sources for 64 bits and 32 bits.
I created a conandata.yml like this 
```
sources:
    "1.8.0_92":
        "Linux":
            "x86_64":
                url: http://****/jni/1.8.0_92/jdk-8u92-linux-x64.tar.gz
                sha256: 79a3f25e9b466cb9e969d1772ea38550de320c88e9119bf8aa11ce8547c39987
            "x86":
                url: http://****/jni/1.8.0_92/jdk-8u92-linux-i586.tar.gz
                sha256: 7203592329877735bb6259844a3a30640edc61920d132f952c40ab2e2014b224
```
Then in the recipe , the source() methode looks like this:
```
def source(self):
        print ("ARCH ",str(self.settings_build.arch))
        try:
            zip_path=self.conan_data["sources"][self.version][str(self.settings_build.os)][str(self.settings_build.arch)]["url"]
            get(self,zip_path,strip_root=True)
        except KeyError:
            raise ConanInvalidConfiguration("Erreur au niveau de la configuration des sources")

```
**Initial state :** there is no packages of jni in cache and i don't want to use conan-center
**Problem** When i create the package in 64 bits, the right sources are downloaded : 

```
conan create . -pr:a=mo_64
...
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    jni/1.8.0_92#24994ac04f3f045fa73cf2b2e16e27c1 - Cache
Python requires
    obj_copy/1.0.0#124cdd60723db9fda2019774e089558c - Cache

======== Computing necessary packages ========
jni/1.8.0_92: Forced build from source
Requirements
    jni/1.8.0_92#24994ac04f3f045fa73cf2b2e16e27c1:bd265bc60dce4388b4696c30a19d8cac101849e5 - Build

======== Installing packages ========
jni/1.8.0_92: Calling source() in /net/users/wawa/.conan2/p/jnib61cbb5a68c07/s
ARCH  x86_64
jni/1.8.0_92: Downloading 181.4MB jdk-8u92-linux-x64.tar.gz
jni/1.8.0_92: Unzipping jdk-8u92-linux-x64.tar.gz to .

-------- Installing package jni/1.8.0_92 (1 of 1) --------
jni/1.8.0_92: Building from source
jni/1.8.0_92: Package jni/1.8.0_92:bd265bc60dce4388b4696c30a19d8cac101849e5
jni/1.8.0_92: Copying sources to build folder

```
Next when i create  a package in 32 bits, it uses the wrong sources already downloaded for bits 64 : 

```
conan create . -pr:a=mo_32
...
======== Input profiles ========
Profile host:
[settings]
arch=x86
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]
arch=x86
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    jni/1.8.0_92#24994ac04f3f045fa73cf2b2e16e27c1 - Cache
Python requires
    obj_copy/1.0.0#124cdd60723db9fda2019774e089558c - Cache

======== Computing necessary packages ========
jni/1.8.0_92: Forced build from source
Requirements
    jni/1.8.0_92#24994ac04f3f045fa73cf2b2e16e27c1:48c232c22db9e1b42712bef3e321f933e4ee8221 - Build

======== Installing packages ========

-------- Installing package jni/1.8.0_92 (1 of 1) --------
jni/1.8.0_92: **Building from source**
jni/1.8.0_92: Package jni/1.8.0_92:48c232c22db9e1b42712bef3e321f933e4ee8221
jni/1.8.0_92: Copying sources to build folder

```
When i delete all recipes of jni in cache, and i create the 32 bits first , it is the right sources (**jdk-8u92-linux-i586.tar.gz**) that are downloaded !!
Did i make something wrong in conandata.yml or in the recipe ?
