### ISSUE TITLE
[feature] Allow rewriting of remote content fetched through conancenter

### ISSUE THREAD

**Issue by FannoFlow1** [conan-io/conan#18164]
### What is your suggestion?

I already have an remote setup for conancenter on artifactory, which is working great to fetch conan deps through a cached layer and have them xray scanned. 

However, the sources for the remote repos are still fetched through the external sites, such as github / gitlab / etc.

I would love a feature to optionally rewrite remote fetch URLs to route through an artifactory VCS proxy or similar 

Example rewrite:

```yaml
sources:
  "3.4":
    url: "https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip"
    sha256: "b5ec004b2712fd08e8861dc271428f048775200a2df719ccf575143ba749a3e9"
  "3.3.8":
    url: "https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.zip"
    sha256: "4d025083cc4a3dd1f91ab9b9ba4f5807193823e565a5bcf4be202669d9911ea6"
  "3.3.7":
    url: "https://github.com/glfw/glfw/releases/download/3.3.7/glfw-3.3.7.zip"
    sha256: "4ef0c544a8ace9a6cd0e0aef8250090f89fea1bf96e9fc1d9d6f76386c290c9c"
patches:
  "3.3.8":
    - patch_file: "patches/3.3.5-0001-Wayland-Remove-extra-cmake-modules-dependency.patch"
      patch_description: "Remove dependency on extra-cmake-modules to fix generation of Wayland Protocols"
      patch_type: "official"
      patch_source: "https://github.com/glfw/glfw/commit/2747e47393cbca2d09db56223e735bd94b21e2eb"
  "3.3.7":
    - patch_file: "patches/3.3.5-0001-Wayland-Remove-extra-cmake-modules-dependency.patch"
      patch_description: "Remove dependency on extra-cmake-modules to fix generation of Wayland Protocols"
      patch_type: "official"
      patch_source: "https://github.com/glfw/glfw/commit/2747e47393cbca2d09db56223e735bd94b21e2eb"
  "3.3.6":
    - patch_file: "patches/3.3.5-0001-Wayland-Remove-extra-cmake-modules-dependency.patch"
      patch_description: "Remove dependency on extra-cmake-modules to fix generation of Wayland Protocols"
      patch_type: "official"
      patch_source: "https://github.com/glfw/glfw/commit/2747e47393cbca2d09db56223e735bd94b21e2eb"
```

-->

```yaml
sources:
  "3.4":
    url: "https://arifactory.company.com/artifactory/github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip"
    sha256: "b5ec004b2712fd08e8861dc271428f048775200a2df719ccf575143ba749a3e9"
  "3.3.8":
    url: "https://arifactory.company.com/artifactory/github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.zip"
    sha256: "4d025083cc4a3dd1f91ab9b9ba4f5807193823e565a5bcf4be202669d9911ea6"
  "3.3.7":
    url: "https://arifactory.company.com/artifactory/github.com/releases/download/3.3.7/glfw-3.3.7.zip"
    sha256: "4ef0c544a8ace9a6cd0e0aef8250090f89fea1bf96e9fc1d9d6f76386c290c9c"
patches:
  "3.3.8":
    - patch_file: "patches/3.3.5-0001-Wayland-Remove-extra-cmake-modules-dependency.patch"
      patch_description: "Remove dependency on extra-cmake-modules to fix generation of Wayland Protocols"
      patch_type: "official"
      patch_source: "https://arifactory.company.com/artifactory/github.com/glfw/glfw/commit/2747e47393cbca2d09db56223e735bd94b21e2eb"
  "3.3.7":
    - patch_file: "patches/3.3.5-0001-Wayland-Remove-extra-cmake-modules-dependency.patch"
      patch_description: "Remove dependency on extra-cmake-modules to fix generation of Wayland Protocols"
      patch_type: "official"
      patch_source: "https://arifactory.company.com/artifactory/github.com/glfw/glfw/commit/2747e47393cbca2d09db56223e735bd94b21e2eb"
  "3.3.6":
    - patch_file: "patches/3.3.5-0001-Wayland-Remove-extra-cmake-modules-dependency.patch"
      patch_description: "Remove dependency on extra-cmake-modules to fix generation of Wayland Protocols"
      patch_type: "official"
      patch_source: "https://arifactory.company.com/artifactory/github.com/glfw/glfw/commit/2747e47393cbca2d09db56223e735bd94b21e2eb"
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide
