### ISSUE TITLE
[workspace] Why require version numbers?

### ISSUE THREAD

**Issue by kenfred** [conan-io/conan#18270]
Why do the packages in the workspace file need to include version numbers? Isn't it true that:

In a build context, only one version of a package is allowed
All packages in the workspace will be part of the same build context
If so, there is no possibility of having:

```yaml
packages:
   dep1/0.1:
      path: dep1
   dep1/0.2:
      path: other_dep1
```

I assume using the same package name in this list will be an error.

A couple other reasons why I'd expect version numbers to not be here:

The package is under development, unreleased. So in the context of a workspace, it is versionless.
In a monorepo or git submodule situation where you check in the workspace file, you may not bother to ever version your packages.
