### ISSUE TITLE
[bug] Libm not lincking cross compiling qt 5.15.16

### ISSUE THREAD

**Issue by jeroqui** [conan-io/conan#18492]
### Describe the bug

I'm trying to crosscompile qt/5.15.16 from a linux machine for a windows host.

Running `conan install . --build=missing -pr:b=default -pr:h=windows-x86_64` I get the following error message:

```
...
Performing shadow build...
Preparing build tree...
Creating qmake...
/usr/bin/ld: qcborvalue.o: undefined reference to symbol 'round@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:194: ../bin/qmake] Error 1

qt/5.15.16: ERROR:
Package '4cb08578df5b4d86f4b62d9417d56c881f0bd322' build failed
qt/5.15.16: WARN: Build folder /root/.conan2/p/b/qtc60b421cd8697/b
ERROR: qt/5.15.16: Error in build() method, line 887
	self.run("%s %s" % (os.path.join(self.source_folder, "qt5", "configure"), " ".join(args)))
	ConanException: Error 2 while executing
```

I tried setting `-lm` on `LDFLAGS`, `CXXFLAGS` and `LIBS` everywhere I could, but I still don't get it to compile.

### How to reproduce it

I managed to create a Docker enviroment to reproduce the error.

`.conan/profiles/default`
```toml
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=13
compiler.libcxx=libstdc++11
compiler.cppstd=20
os=Linux

[conf]
tools.system.package_manager:mode=install

[buildenv]
LDFLAGS=-lm
CXXFLAGS=-lm
LIBS=-lm

CROSS_COMPILE = x86_64-w64-mingw32-

```

`.conan/profiles/windows-x86_64`
```toml
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=13
compiler.libcxx=libstdc++11
compiler.threads=win32
compiler.exception=seh
os=Windows

[buildenv]
CC=x86_64-w64-mingw32-gcc
CXX=x86_64-w64-mingw32-g++
AR=x86_64-w64-mingw32-ar
RANLIB=x86_64-w64-mingw32-ranlib
STRIP=x86_64-w64-mingw32-strip
RC=x86_64-w64-mingw32-windres
WINDRES=x86_64-w64-mingw32-windres
AS=nasm
PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig
LDFLAGS=-L/usr/x86_64-w64-mingw32/lib -lpthread
LIBRARY_PATH=/usr/x86_64-w64-mingw32/lib
CONAN_CMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

[conf]
tools.system.package_manager:mode=install
tools.build:compiler_executables={"c": "x86_64-w64-mingw32-gcc", "cpp": "x86_64-w64-mingw32-g++", "rc": "x86_64-w64-mingw32-windres", "ar": "x86_64-w64-mingw32-ar", "strip": "x86_64-w64-mingw32-strip"}
tools.build:skip_test=True
```

`Dockerfile`
```Dockerfile
FROM ubuntu:24.10

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    make \
    g++-13 \
    gcc-13 \
    cpp \
    perl \
    mingw-w64 \
    mingw-w64-tools \
    mingw-w64-x86-64-dev \
    mingw-w64-common

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 130 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-13 \
    --slave /usr/bin/gcov gcov /usr/bin/gcov-13 \
    --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-13 \
    --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-13 \
    --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-13 && \
    ln -sf /usr/bin/gcc /usr/bin/cc

RUN pip install -U conan cmake==3.15.3.post1 --break-system-packages



# Create Conan profiles directory
RUN mkdir -p /root/.conan2/profiles

RUN useradd -m -s /bin/bash user
USER user

WORKDIR /home/user/app

# Copy project files and configuration files
COPY --chown=user:user . .
COPY --chown=user:user .conan/profiles/default /root/.conan2/profiles/
COPY --chown=user:user .conan/profiles/windows-x86_64 /root/.conan2/profiles/

# Switch back to root for Conan operations
USER root


CMD ["conan", "install", ".", "--output-folder=-conan", "--build=*", "-pr:b=default", "-pr:h=windows-x86_64"]

```

`conanfile.py`
```python
from conan import ConanFile
from conan.tools.cmake import cmake_layout

class QtTest(ConanFile):
    name = "QtTest"
    version = "1.0"
    settings = "os", "arch", "compiler", "build_type"
    generators = "CMakeDeps", "CMakeToolChain"
    default_options = {
        "qt/*:with_mysql": False,
        "qt/*:cross_compile": "x86_64-w64-mingw32-",
    }

    def layout(self):
        cmake_layout(self)

    def requirements(self):
        self.requires("qt/5.15.16")

```
