### ISSUE TITLE
Improve option conflict errors

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#2547]
Conan version: 1.0.4

In some cases an error such as the following may be reported by conan:

```
ERROR: libidn/1.33-4@plex/stable: gnutls/3.4.16-8@plex/stable tried to change libidn/1.33-4@plex/stable option opus:shared to True
but it was already assigned to False by None
```

In this message, "None" is quite confusing. It would be better to report PROJECT or consuming conanfile (but in some convoluted cases that might not even be true, so if there was a way to trace all option changes as they happen, that would be a huge benefit).

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi @sztomi 

I'm trying to reproduce your error in order to enhance that message, we all agree that we have to give meaningful information instead of `None`... but I'm not able to configure a minimum project with its dependencies and get that error. If it still exists, can you help me to reproduce it?

Thanks!

**Comment by sztomi** [comment]
@jgsogo I don't have a conanfile that reproduces this easily unfortunately. In hindsight, I should have created a minimal repro right then. I think it should be still possible to create one though. What happens here is that the main conanfile (`libidn/1.33-4@plex/stable`) sets an option *of a dependency* that conflicts with one set in a dependency that requires the same. In this case (I think):

```
  - libidn/1.33-4@plex/stable
     - options:
       - opus:shared=False
     - requires:
         - opus/1.0@plex/stable
         - gnutls/3.4.16-8@plex/stable
             - requires:
               - opus/1.0@plex/stable
             - options:
               - opus:shared=True
```

So `libidn` depends on `opus` and `gnutls` and sets `opus:shared` to False. `gnutls` also depends on `opus`, but sets `opus:shared` to True.
