### ISSUE TITLE
Allow None as subsettings in settings.yml

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2811]
They shouldn't need definition in command line or profiles, should be like a None value in a list of possible values in settings.yml

```
Linux:
       distro:
           None:
           Ubuntu:
           Yocto:
               version: ["sumo", "rocko"]
```
