### ISSUE TITLE
[workspace] how to add multiple includedirs

### ISSUE THREAD

**Issue by GarrickLin** [conan-io/conan#3855]
I modified [conan-workspace-example](https://github.com/memsharded/conan-workspace-example) by adding another header folder into `HelloB`. But it doesn't works. So how to add multiple includedirs ? It is possible to use my predifined cached cmake variable in dependent package ?
```
HelloB:
    folder: B
    includedirs: src, src/include # add another header here
    cmakedir: src
HelloC:
    folder: C
    includedirs: src
    cmakedir: src
HelloA:
    folder: A
    cmakedir: src

root: HelloA
generator: cmake
name: MyProject
```

**Comment by GarrickLin** [comment]
Since it is not mentioned in documemnts, I have to refer to the source code. And I found it out that we should use it in the following way:
```
HelloB:
    folder: B
    includedirs: [src, src/include] # the source will parse it as a list
    cmakedir: src
HelloC:
    folder: C
    includedirs: src
    cmakedir: src
HelloA:
    folder: A
    cmakedir: src

root: HelloA
generator: cmake
name: MyProject
```
with brackets will solve this problem.
