### ISSUE TITLE
CMake Warning:  Manually-specified variables are not used by the project:

### ISSUE THREAD

**Issue by henryJack** [conan-io/conan#4236]
I get a warning when I run `conan create` for my project on Ubuntu with `conanfile.py`

```python
from conans import ConanFile, CMake
import os

class OrchestraPhysicalConan(ConanFile):
    name = "OrchestraPhysical"
    if('CI_COMMIT_TAG' in os.environ):
        version = os.environ['CI_COMMIT_TAG']
    license = "Closed"
    author = "Romax Technology: Math Squad"
    url = "https://gitlab.romaxtech.com/orchestra/c/orchestraphysical"
    description = "A class library for all physical objects we use in Orchestra"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = "shared=False", "fPIC=True"
    generators = "cmake"
    exports_sources = "PhysicalFramework/*", "CMakeLists.txt"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include", src="PhysicalFramework")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.dylib*", dst="lib", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["OrchestraPhysical"]
```

I get the following warning when I run `conan create`...

```CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    CONAN_CMAKE_POSITION_INDEPENDENT_CODE
    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_CXX_FLAGS
    CONAN_C_FLAGS
    CONAN_EXPORTED
    CONAN_IN_LOCAL_CACHE
    CONAN_LIBCXX
    CONAN_SHARED_LINKER_FLAGS
```

And the following error when it's consumed by another package:

```
relocation R_X86_64_32 against __pthread_key_create can not be used when making a shared object; recompile with -fPIC
```

This is probably because  `CONAN_CMAKE_POSITION_INDEPENDENT_CODE` option is not being picked up from the `conanfile.py`. I could just hack this into the CMAKE file but I should really understand why conan inst working as expected.

Any Ideas how to fix this?

**Comment by memsharded** [comment]
Hi @henryJack 

First, some quick feedback. You can get the version in oneliner:

```python
# That will return None if the var is not defined
version = os.getenv('CI_COMMIT_TAG')
```

I'd need to have some idea about your ``CMakeLists.txt``. It seems that you might not be using the

```CMake
include(.../conanbuildinfo.cmake)
conan_basic_setup()
```

lines.

Those lines convert the information passed by conan variables, like CONAN_XXXX, to real cmake configuration. The idea is that conan never implictly changes your build system, so you have full control of what is happening. Please check adding those lines and tell me. Thanks!

**Comment by henryJack** [comment]
Hi, thanks for the help, tried adding this but says it cant find --> 

![image](https://user-images.githubusercontent.com/22593502/50824025-5c081380-132d-11e9-8356-f8aa4b23e9c3.png)

**Comment by memsharded** [comment]
Hi @henryJack 

Sorry for that, that was pseudo-code, and that was an elipsis, to save some typing.

From: https://docs.conan.io/en/latest/getting_started.html

the lines are:

```cmake
 include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 conan_basic_setup()
```

**Comment by henryJack** [comment]
My CMAKE file is

```
cmake_minimum_required(VERSION 2.8.9)


enable_language(C)
enable_language(CXX)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

project(PhysicalFramework)

 include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 conan_basic_setup()


file(GLOB SOURCES "PhysicalFramework/*.cpp")
include_directories(${PROJECT_SOURCE_DIR}/PhysicalFramework)
add_library(PhysicalFramework ${SOURCES})

if(TESTING)
find_package(GTest REQUIRED)
include_directories(${GTEST_INCLUDE_DIRS})
include_directories(${PROJECT_SOURCE_DIR}/PhysicalFrameworkTest)


file(GLOB TEST_SOURCES "PhysicalFrameworkTest/*.cpp")
add_executable(unit_tests ${TEST_SOURCES})

target_link_libraries(
    unit_tests
    ${GTEST_LIBRARIES}
    PhysicalFramework
    pthread
    )

include(CTest)
enable_testing()
add_test(unit ${PROJECT_BINARY_DIR}/unit_tests)
endif(TESTING)

```

I get the following error:

```
$ cmake -DBUILD_SHARED_LIBS=ON ..
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:12 (include):
  include could not find load file:

    /builds/orchestra/c/orchestraphysical/build/conanbuildinfo.cmake


CMake Error at CMakeLists.txt:13 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".


-- Configuring incomplete, errors occurred!
```

The pipeline looks like this:

```
image: continuumio/miniconda3:4.3.27p0

stages:
  - compile
  - test
  - deploy
  

compile_linux:
   stage: compile
   script:
    - apt update
    - apt-get install build-essential -y
    - apt-get install cmake -y
    - pip install conan
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DBUILD_SHARED_LIBS=ON ..
    - make PhysicalFramework
    - cmake -DBUILD_SHARED_LIBS=OFF ..
    - make PhysicalFramework
   artifacts:
    expire_in: 1 hour
    name: "build-linux"
    paths:
     - ./PhysicalFramework/*.h
     - ./build/*.a
     - ./build/*.so


test_linux:
   stage: test
   script:
    - apt update
    - apt-get install build-essential -y
    - apt-get install cmake -y
    - pip install conan
    - apt-get install libgtest-dev
    - pushd /usr/src/gtest/
    - cmake /usr/src/gtest/CMakeLists.txt
    - make 
    - cp *.a /usr/lib
    - popd
    - ls
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -D TESTING=TRUE ..
    - make unit_tests
    - ctest --output-on-failure

deploy_conan:
   only:
    - tags
   stage: deploy
   script:
    - apt update
    - apt install build-essential -y
    - apt install -y cmake
    - apt install -y git
    - pip install conan
    - conan remote add neils_pc http://172.16.22.142:9300/
    - conan user -r=neils_pc romax -p=password123
    - conan create . romax/release
    - conan upload OrchestraPhysical/${CI_COMMIT_TAG}@romax/release --all -r=neils_pc
```
