### ISSUE TITLE
[workspaces] Random order of subdirectories in generated CMakeLists.txt

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4558]
The order of add_subdirectory commands in the generated CMakeLists.txt appears random.

With 
```
base:
  folder: base
  includedirs: main/a main/b
  cmakedir: main

dependent:
  folder: dependent
  cmakedir: main

root: dependent
generator: cmake
name: MyProject
```
I sometimes get 
```
# conanws
cmake_minimum_required(VERSION 3.3)
project(MyProject CXX)
add_subdirectory(dependent/main "/home/travis/build/sigiesec/conan-cmake-export-example/build/dependent/")
add_subdirectory(base/main "/home/travis/build/sigiesec/conan-cmake-export-example/build/base/")
```
instead of the expected
```
# conanws
cmake_minimum_required(VERSION 3.3)
project(MyProject CXX)
add_subdirectory(base/main "/home/travis/build/sigiesec/conan-cmake-export-example/build/base/")
add_subdirectory(dependent/main "/home/travis/build/sigiesec/conan-cmake-export-example/build/dependent/")
```
See, e.g., here: https://travis-ci.org/sigiesec/conan-cmake-export-example/jobs/494915886#L6041

Since the order is significant, I would expect that the order from the conanws.yml is preserved, as the dependencies are not explicitly specified.

This issue occurred with conan 1.12.3

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
