### ISSUE TITLE
[workspaces] Handling of transitive requirements broken

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4720]
With conan 1.13.0, the handling of transitive requirements appears broken. I don't have a reproducible test case right now (I can try to construct one), but the situation is as follows:

I want to have a workspace with packages A and B. A depends on C, which has a transitive requirement on D. B depends on D directly.

If I run a regular conan install for A, the conanbuildinfo.cmake contains the definitions for C and D, in particular the CONAN_CMAKE_MODULE_PATH contains both C's and D's directories, which is necessary to process the cmake files of C.

However, with conan workspace install, only B's conanbuildinfo.cmake contains the definitions for D, while A's conanbuildinfo.cmake containts only the definitions for C, which leads to cmake errors, since D's cmake modules cannot be found.

**Comment by memsharded** [comment]
While having a look at this issue I discovered a bug with the management of multiple "root" packages in a workspace. I have submitted a fix in #4722 

It was failing when declaring:
```yaml
 editables:
                HelloD/0.1@lasote/stable:
                    path: D
                HelloB/0.1@lasote/stable:
                    path: B
                HelloC/0.1@lasote/stable:
                    path: C
                HelloA/0.1@lasote/stable:
                    path: A
            layout: layout
            root: HelloA/0.1@lasote/stable, HelloB/0.1@lasote/stable
```

Once the bug is fixed, it seems that the conanbuildinfo.cmake files of each editable package contains the right information. It is necessary to have a ``[build_folder]`` in the used layouts.

Please have a look to the test here: https://github.com/conan-io/conan/pull/4722/files. Thanks!
