### ISSUE TITLE
[workspaces] Propagation of default options for transitive dependencies

### ISSUE THREAD

**Issue by onnodb** [conan-io/conan#4751]
We've been trying out the revamped "workspaces" feature in Conan 1.13. My tests have been done using a project using CMake 3.13 on Windows, with the MSVC toolchain.

We have a project that consists of: 
* a consumer project `C`, with dependencies on package `P` and library `A`;
* a homegrown package `P`, that also depends on `A`;
* a library `A` with a `conanfile.py` that provides an option called `shared`.

The `conanfile.py` for `C` furthermore has the following line:
```py
class CConan(ConanFile):
    # ...
    default_options = "A:shared=True"
```

The workspace feature gives us a nice local editing workflow for `C` and `P`. Following the (very clear!) instructions in the documentation, we create a `workspace.yml` file:
```yaml
editables:
  C/1.0.0@example/testing:
    path: C
  P/1.0.0@example/testing:
    path: P
layout: mylayout
workspace_generator: cmake
root: C/1.0.0@example/testing
```

Now, when compiling the super-project generated by `conan workspace install`, we noticed that the `A:shared=True` option does not seem to be propagated from `C` to `P` anymore, resulting in linker errors. This propagation does work absolutely fine when using the normal "editable package" workflow (`conan editable`), or the normal workflow (`conan install`).

Thanks for your help!
