### ISSUE TITLE
[suggestion] Recommend adding "Bare-metal" to default settings.yml 

### ISSUE THREAD

**Issue by ericjameszimmerman** [conan-io/conan#4798]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.11.1
os: Windows 10

Suggestion to add "Bare-metal" or some variation as an "os" option for software without an "os".

e.g.
```
    FreeBSD:
    SunOS:
    Arduino:
    Bare-metal:
        board: ANY
```
