### ISSUE TITLE
[Feature] Pass 'workspace_folder' value to the layout files

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4840]
Hi!

I think it will be useful to have the ``workspace_folder`` value available in the layout files, it will allow to define all the ``build_folder`` of the editable packages that belongs to the workspace inside the same directory, let me show you an example:

 * Given a workspace definition:

   ```yaml
           editables:
                HelloB/0.1@lasote/stable:
                    path: /path/to/some/place/B
                HelloC/0.1@lasote/stable:
                    path: /mywork/dev/path/HelloC
                HelloA/0.1@lasote/stable:
                    path: /this/is/HelloA
            layout: layout
            workspace_generator: cmake
            root: HelloA/0.1@lasote/stable
    ```

 * The layout file could be

    ```ini
    ...
    [build_folder]
    {{ workspace_folder }}/build/{{ reference.name }}
    ```

Take into account that this variable will only be available when working with workspaces, so the layout file should add some conditions if it is going to be used for editable packages too.

Some preliminar work can be found [here](https://github.com/conan-io/conan/compare/develop...jgsogo:feature/workspace-path-in-editable-layout?expand=1) (not even a POC)
