### ISSUE TITLE
Conan doesn't work with LGTM

### ISSUE THREAD

**Issue by Milerius** [conan-io/conan#4911]
Hey according to https://lgtm.com/logs/9b499adc6e40565e44a55c4c9ec8c78af714e830/lang:cpp

Conan version 1.14.1

i cannot setup LGTM with Conan:
```
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)
```

I have absolutely no idea why i got this error, there is my lgtm.yml:
```yml
extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - python-pip
    after_prepare:    # Customizable step used by all languages.
      - pip3 install --local cmake conan
      - pip3 install --local cmake conan --upgrade
      - ls ~/.local/bin
      - export PATH=$PATH:~/.local/bin
      - conan --version
      - cmake --version
      - conan profile new default --detect
      - conan profile update settings.compiler.version=8 default
      - conan profile update settings.compiler.libcxx=libstdc++11 default
      - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - conan remote add skypjack https://api.bintray.com/conan/skypjack/conan
      - mkdir $LGTM_SRC/build
      - cd $LGTM_SRC/build
      - conan install ../
      - cd -
```

If anyone have build conan project with lgtm, please let me know
