### ISSUE TITLE
[workspaces] Incorrect build order

### ISSUE THREAD

**Issue by izzyreal** [conan-io/conan#5072]
Conan version: 1.14.3

I have this conanws.yml
```
editables:
    moduru/0.1@izmar/dev:
        path: moduru
    ctoot/0.1@izmar/dev:
        path: ctoot
    mpc/0.1@izmar/dev:
        path: mpc
    vmpc/0.1@izmar/dev:
        path: vmpc
layout: layout
generators: cmake_multi
workspace_generator: cmake
root: vmpc/0.1@izmar/dev
```
`ctoot` is part of `vmpc`'s required packages. However, when I have made changes in `ctoot`, I need to manually build it, or else `vmpc` will reuse the old build of `ctoot`.
