### ISSUE TITLE
What's the proper way to config conan for Hisilicon build tools.

### ISSUE THREAD

**Issue by Mingyiz** [conan-io/conan#5096]
Hisilicon is SoC (Armv7), and it provide GCC and SDK. I am building lib and application with such toolchain, and I confused how to config the conan settings ( may be profile) ?

for example:
GCC tool chains  Hisi-v300-gcc , is a armv7, gcc4.8.3. I believe the following config is bad choise, because it is same as your official example [Windows to Raspberry Pi (Linux/ARM)](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#windows-to-raspberry-pi-linux-arm), and the Hisi GCC build out will not work on Raspberry PI.
```ini
[settings]
os=Linux
arch=armv7
compiler=gcc
compiler.version=4.8
```

**Comment by memsharded** [comment]
Hi @Mingyiz 

Conan defines some default settings in ``~/.conan/settings.yml`` that are common for typical mainstream platforms. 

I think your case might be one that requires to define your own, custom settings, to properly define things. For example, you might have recipes that define ``settings = "os", "compiler", "build_type",...``, for example for a common library that you use both in your desktop apps and in an embedded system. In the ``settings.yml`` you can find:

```yaml
os:
    Windows:
        subsystem: [None, cygwin, msys, msys2, wsl]
    ....
    Linux:
    Macos:
        version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14"]
    Android:
        api_level: ANY
    iOS:
        version: ["7.0", "7.1", "8.0", "8.1", "8.2", "8.3", "9.0", "9.1", "9.2", "9.3", "10.0", "10.1", "10.2", "10.3", "11.0", "11.1", "11.2", "11.3", "11.4", "12.0", "12.1"]
    watchOS:
        version: ["4.0", "4.1", "4.2", "4.3", "5.0", "5.1"]
    ....
```

But, then what profile would you use for a bare-metal compilation? Certainly none of the above values. In that case you could add ``None`` to the ``os`` setting, or maybe, customize it for your target. for example, imagine that you are targeting different boards, each one should have its different binary (because some have different characteristics, as a math co-processor)
```yaml
os:
    None:
    Hisilicon:
        board: [None, board1, board2, ...]
    Windows:
        subsystem: [None, cygwin, msys, msys2, wsl]
```

If your system is using some kind of Linux OS as platform, you could specialize the settings for the Linux OS only:
```yaml
os:
    Windows:
        subsystem: [None, cygwin, msys, msys2, wsl]
    ....
    Linux:
        platform: [None, Hisilicon, RaspberryPi]
    Macos:
        version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14"] 
    ....
```

Once that is modeled to fit your needs you can write your profiles as:

```
[settings]
os=Linux
os.platform=Hisilicon
arch=armv7
compiler=gcc
compiler.version=4.8
```

And if you need to access the values in your recipe:

```python
def build(self):
     if self.settings.os.platform == "Hisilicon":
          # Do something special here
```

Please tell me if this helps. Thanks!
