### ISSUE TITLE
Add SCM info to package

### ISSUE THREAD

**Issue by mietzen** [conan-io/conan#5234]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I've a feature request:

Now if the revision is set to auto only a minimum of amount of data is stored:

```
scm:
    revision: 58b4cc6cd02345646cf286e1004adf23518d0c
    subfolder: source
    type: git
    url: https://github.com/...
```

I would like to see something like this:

```
scm:
    revision: 58b4cc6cd02345646cf286e1004adf23518d0c
    branch: my-new-stuff
    author: Me
    subfolder: source
    type: git
    url: https://github.com/...
```
Perhaps also the pkg author could be automatically set by the scm
