### ISSUE TITLE
[bug] Linter is not able to detect conan_data member

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5335]
To help us debug your issue please explain:

Conan Version: 1.16.0

Hi!

When using conandata.yml with a recipe and extracting its information by `self.conan_data`, the Linter doesn't detect it as a member of ConanFile.

#### Steps to reproduce

Create a small example with follow files:

```yaml
# conandata.yml
sources:
  2.3:
    url: "https://github.com/google/cctz/archive/v2.3.tar.gz"
    sha256: "8615b20d4e33e02a271c3b93a3b208e3d7d5d66880f5f6208b03426e448f32db"
```

```python
# conanfile.py
from conans import ConanFile, tools

class CCTZConan(ConanFile):
    name = "cctz"
    settings = "os", "arch", "compiler", "build_type"

    def source(self):
        tools.get(**self.conan_data["sources"][float(self.version)])
```

Now execute the follow command

`conan create . 2.3@conan/testing`

#### Expected Result

Conan is able to build without any warning

#### Actual Result

```
Exporting package recipe
Linter warnings
    WARN: Linter. Line 8: Instance of 'CCTZConan' has no 'conan_data' member
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
