### ISSUE TITLE
[question] add custom attribute 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#5976]
Is there a way to add custom attribute to a conan package that can be checked using the command `conan inspect` ?

For example, the current output of `conan inspect zlib/1.2.11@conan/stable` is

```
name: zlib
version: 1.2.11
url: http://github.com/conan-community/conan-zlib
homepage: https://zlib.net
license: Zlib
author: Conan Community
description: A Massively Spiffy Yet Delicately Unobtrusive Compression Library (Also Free, Not to Mention Unencumbered by Patents)
topics: ('conan', 'zlib', 'compression', 'zip')
generators: cmake
exports: ['LICENSE']
exports_sources: ['CMakeLists.txt', 'CMakeLists_minizip.txt', 'minizip.patch']
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'arch', 'compiler', 'build_type')
options:
    fPIC: [True, False]
    minizip: [True, False]
    shared: [True, False]
default_options:
    fPIC: True
    minizip: False
    shared: False
```

We want to extend this list by adding the git commit hash for example.

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
