### ISSUE TITLE
[question] Does conan support multiple sources url in conandata.yml?

### ISSUE THREAD

**Issue by leyewen** [conan-io/conan#6349]
In some country or region, abominable gateway forbid to visit foreign country some website.
Some development sites, some source code download sites can not be use!

I hope to `conandata.yml` support config multiple sources url, and it can auto switch!
eg:
```
sources:
  2.10.1:
    sha256: 3a60d391fd579440561bf0e7f31af2222bc610ad6ce4d9d7bd2165bca8669110
    url: https://download.savannah.gnu.org/releases//freetype/freetype-2.10.1.tar.gz
```
```
sources:
  2.10.1:
    sha256: 3a60d391fd579440561bf0e7f31af2222bc610ad6ce4d9d7bd2165bca8669110
    url: [
        "https://download.savannah.gnu.org/releases//freetype/freetype-2.10.1.tar.gz",
        "http://mirrors.ocf.berkeley.edu/gnu/releases//freetype/freetype-2.10.1.tar.gz",
        "https://mirrors.ustc.edu.cn/gnu/releases//freetype/freetype-2.10.1.tar.gz"
    ]
```
