### ISSUE TITLE
Conan io with gcc cross-compiler

### ISSUE THREAD

**Issue by mldmelissa** [conan-io/conan#675]
Has anyone tried using conan io with a gcc cross compiler? Right now I am working in Atmel Studio 7. Atmel studio uses a arm-gcc compiler.

**Comment by lasote** [comment]
Hi @mldmelissa. We have a pending discussion and a PR #333 related to cross compiling and embedded system. Should be great if you start working on it and give us feedback. I'm sure that @astralien3000 could help us with your doubts.

If you know how to invoke your arm-gcc compiler in command line I bet you can make a conan package for your libraries easily.

Let me know if we can help you to start with it or any other doubt.

**Comment by astralien3000** [comment]
Hello, I use often conan with avr-gcc and arm-none-eabi-gcc.
Disclaimer : #333 is a bit outdated, and would not work as-is. But you can deduce some modifications to be done.

You may first modify your settings.yml : 
```yaml
os: [Windows, Linux, Macos, Android, iOS]
arch: [x86, x86_64, ppc64le, armv6, armv7, armv7hf, armv8]
compiler:
    gcc:
        version: ["4.4", "4.5", "4.6", "4.7", "4.8", "4.9", "5.1", "5.2", "5.3", "5.4", "6.1", "6.2"]
        libcxx: [libstdc++, libstdc++11]
        threads: [None, posix, win32] #  Windows MinGW
        exception: [None, dwarf2, sjlj, seh] # Windows MinGW
    Visual Studio:
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14"]
    clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9"]
        libcxx: [libstdc++, libstdc++11, libc++]
    apple-clang:
        version: ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0"]
        libcxx: [libstdc++, libc++]
    arm-none-eabi-gcc:
        version: ["5.2"]
    avr-gcc:
        version: ["4.9"]
build_type: [None, Debug, Release]
target: ANY
```

I added avr-gcc and arm-none-eabi-gcc to the compilers, with the version available on my system.
I also added a settings called `target` to specify the microcontroller, if needed.
