### ISSUE TITLE
[bug] conandata.yml does not support HTTP authentication

### ISSUE THREAD

**Issue by jheaff1** [conan-io/conan#6852]
### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 7.7.1908 x86_64
  * Compiler+version: gcc 4.8
  * Conan version: 1.24.0
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)
In a Conan package recipe's conandata.yml file, attempt to add HTTP authentication. (username and password tuple).

ie:
```yaml
sources:
  1.0.0:
    sha256: 8c48baf3babe0d505d16cfc0cf272589c66d3624264098213db0fb00034728e9
    url: https://my.url/my-package-1.0.0.tar.gz
   auth: ('username', 'password')
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
From "conan create .. package_name@":

```bash
ERROR: Error downloading file https://my.url/my-package-1.0.0.tar.gz: ''str' object is not callable'
```

The "download" function of the Conan "tools" python module expects the "auth" argument to be a tuple of a username and a password. This is documented here: https://docs.conan.io/en/latest/reference/tools.html

"auth (Optional, Defaulted to None): A tuple of user and password to use HTTPBasic authentication"

The conans.client Python module uses "yaml.safe_load" to parse the conandata.yml file. PyYAMLs safe loader does not support tuples. Consequently, it is not possible to add HTTP authentication to a conandata.yml file.

My requirement for HTTP authentication is that the source tarballs I need to download when creating my Conan package is hosted on an internal corporate website and requires HTTP authentication. As such, this is a high priority issue for me.
