### ISSUE TITLE
[bug] 'Visual Studio' settings are incorrect.

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#7019]
To date there are following settings for 'Visual Studio' compiler:
```yaml
compiler:
    Visual Studio: &visual_studio
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15", "16"]
        toolset: [None, v90, v100, v110, v110_xp, v120, v120_xp,
                  v140, v140_xp, v140_clang_c2, LLVM-vs2012, LLVM-vs2012_xp,
                  LLVM-vs2013, LLVM-vs2013_xp, LLVM-vs2014, LLVM-vs2014_xp,
                  LLVM-vs2017, LLVM-vs2017_xp, v141, v141_xp, v141_clang_c2, v142]
        cppstd: [None, 14, 17, 20]
```
The item ` runtime:` should have the following values: `[dynamic, static]`

**The reasons:**

You can not use flags `MDd, MTd` in release builds (and vice versa):
1. There is the special warning for this case - https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4098?view=vs-2019
2. The docs clearly stated
> https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019
> To build a debug version of your application, the _DEBUG flag must be defined and the application must be linked with a debug version of one of these libraries.
3. Debug libraries use special version of memory allocation functions, and mixing them with release version is not a good idea - https://docs.microsoft.com/en-us/visualstudio/debugger/debug-versions-of-heap-allocation-functions?view=vs-2019
