### ISSUE TITLE
[bug] No module named setuptools

### ISSUE THREAD

**Issue by Yuri6037** [conan-io/conan#7092]
Unable to install conan package manager on Github Actions: pip3 install fails with "No module named setuptools".
If there is a required dependency then conan should explicitly specify it in the python pip package.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: No idea what Github Actions uses probably gcc
  * Conan version: Not applicable; could not even install it
  * Python version: No idea what python version Github Actions uses probably python 3

### Steps to reproduce (Include if Applicable)
Just run pip3 install conan and enjoy the fail on Github Actions

### Logs (Executed commands with output) (Include/Attach if Applicable)

```python
Collecting conan
  Downloading https://files.pythonhosted.org/packages/2b/63/18c12ffbf20e0f30ecaad6fc4ccfc480973d505210c8c74ad192789597d6/conan-1.25.2.tar.gz (581kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
```

EDIT: Also tried python 2.7, even worse, I get spammed of these errors in console:

```python
Building wheels for collected packages: conan, PyYAML, bottle, future, node-semver, patch-ng, pluginbase
  Running setup.py bdist_wheel for conan: started
  Running setup.py bdist_wheel for conan: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Xbn2bJ/conan/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp7ER3jjpip-wheel- --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  Failed building wheel for conan
  error: invalid command 'bdist_wheel'
```

**Comment by uilianries** [comment]
Hi @Yuri6037!

Could you please share your yaml file with the workflow description?

Currently, I use Conan + Github Actions, maybe some dependency is missing in your setup.

Anyway, I would say you need to install `python-setuptools` before:

    sudo apt-get install -y python-setuptools

**Comment by Yuri6037** [comment]
Here is my YAML

```yaml
name: Build & Debug

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches-ignore: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        pip3 install conan
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Test
      run: ./Debug/BPF.Tests
```

EDIT: After forcing install for python-setuptools I get same error and apt says:

```bash
python-setuptools is already the newest version (39.0.1-2).
python-setuptools set to manually installed.
```

**Comment by Yuri6037** [comment]
I found a workarround:

```bash
sudo pip3 install setuptools
sudo pip3 install conan
```

It seem that conan does not have the correct dependencies listed in the python pip package. I think conan should list setuptools as a dependency.

**Comment by uilianries** [comment]
@Yuri6037 You should use Python setup for Github Actions. That's well documented: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

Please, update your yaml file:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Prepare
      run: |
        python -m pip install conan
```
