### ISSUE TITLE
[bug] conanfile.txt not found when using Github Actions

### ISSUE THREAD

**Issue by noctera** [conan-io/conan#8307]
I want to setup a workflow with Github Actions, but unfortunately conan is telling me that it didn't find my conanfile.txt although it is showing up when executing ls
```
Run ls && whereis conanfile.txt
CMakeLists.txt
CODE_OF_CONDUCT.md
Dockerfile
LICENSE
README.md
conanfile.txt
docker-compose.yml
images
serverSettings.json
src
```

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version: 1.32.1
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)
I'm using this Github Action script
```
name: Catch2 Testing
on: push

jobs:
  build:
    name: Run Catch2 Testing
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
            packages: conan
      - run: ls
      - run: mkdir build && cd build
      - run: conan install -s compiler.libcxx=libstdc++11 .. --build=missing 
      - run: cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -S . -B build && cmake --build build
      - run: cd build/bin && ./vocascan-server-testing
```
As you can see I'm installing conan with ```pip install```, create a build folder, cd into it and call ```conan install``` as the introduction page in the Documentation tells. This works when running it on my lokal machine, but when executing these commands in Github Actions conanfile.txt can't be found

### Logs (Executed commands with output) (Include/Attach if Applicable)
The output of ```- run: conan install -s compiler.libcxx=libstdc++11 .. --build=missing ``` is:

```
Auto detecting your dev setup to initialize the default profile (/home/runner/.conan/profiles/default)
Found gcc 7
Found clang 9.0
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/runner/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=7
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /home/runner/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


ERROR: Conanfile not found at /home/runner/work/vocascan-server/conanfile.py or /home/runner/work/vocascan-server/conanfile.txt
Error: Process completed with exit code 1.
```
Or if you want to see the whole Github Actions Log see [this](https://github.com/noctera/vocascan-server/runs/1670103837?check_suite_focus=true)
I hope someone can help me with my problem.
Thanks in advance :)
