### ISSUE TITLE
[question] How-to upgrade conan v1.9 in docker?

### ISSUE THREAD

**Issue by itdoginfo** [conan-io/conan#8471]
I have conan_server version 1.9.2 in docker. Run using a compose file:
```
version: '3.7'
services:
  conan-test:
    image: conanio/conan_server:1.9.2
    restart: always
    ports:
      - "9400:9300"
    volumes:
        - "./conan_server:/root/.conan_server"
```

I am trying to update for example to conanio/conan_server:1.14.1, just docker-compose up
```
conan-test_1  | [2021-02-09 13:33:59 +0000] [15] [INFO] Worker exiting (pid: 15)
conan-test_1  | **********************************************
conan-test_1  | *                                            *
conan-test_1  | *      ERROR: STORAGE MIGRATION NEEDED!      *
conan-test_1  | *                                            *
conan-test_1  | **********************************************
conan-test_1  | A migration of your storage is needed, please backup first the storage directory and run:
conan-test_1  | 
conan-test_1  | $ conan_server --migrate
```
Ok, add command to docker-compose
```
    command: sh -c "conan_server --migrate" 
```
And up
```
conan-test_1  | sh: conan_server: not found
```
Also I tried with the latest version 1.33.0, the result is the same.
The only thing I found in the documentation on this topic
https://docs.conan.io/en/latest/faq/troubleshooting.html?highlight=migrate#error-error-while-starting-conan-server-with-multiple-workers

Is there a way to do this in docker?
