### ISSUE TITLE
How to add custom build_type values?

### ISSUE THREAD

**Issue by crazydef** [conan-io/conan#8629]
The pre-defined `build_type` values are incompatible with our setup.

I can see the existing values are listed in settings.yml, but is it possible to add custom types programmatically?  (We need to be able to define these when building on our Azure hosted build machines.)

**Comment by crazydef** [comment]
I figured out how to install a custom settings file.

If anyone else needs this for a Azure hosted build:

Create a copy of your settings.yml (it must still be called settings.yml), make whatever changes you need, and include it in your source repo.  (Or add a build step to fetch it from another repo.)

Add a new step to your pipeline yaml to install the modified settings:
```
- task: ArtifactoryConan@1
  inputs:
    conanCommand: 'Custom'
    customArguments: 'config install <full_path_to_your_settings.yml>'
    collectBuildInfo: false
  displayName: Update Conan settings
```

Now any subsequent Conan tasks will be able to use the modified settings.
