### ISSUE TITLE
[question] Conan workspace without specifying versions of editables or using wildcards?

### ISSUE THREAD

**Issue by Ambrase** [conan-io/conan#8674]
Is it possible to use the Conan workspace without specifying versions of editables or using wildcards for versions? I don't want to bump versions workspace yml each time when I bump versions in my editables. 

Something like

```
editables:
    say:
        path: say
    hello:
        path: hello
    chat:
        path: chat
layout: layout_gcc
workspace_generator: cmake
root: chat
```

Is it supported somehow?

Thanks

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
