### ISSUE TITLE
[feature] add QNX stdlib libc++/libstdc++ support to settings.yml

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#9464]
Hi there,
my feture request is to add the following elements to the ```settings.yml```.
qcc -> libcxx -> "libc++" and "libstdc++"

### Background
Since QNX 7.0 the compiler QCC supports the parameter ```stdlib```. This selects the C++ library the compiler uses, as QNX supports different C++ library implementations out-of-the-box ([see docs here](https://www.qnx.com/developers/docs/7.0.0/index.html#com.qnx.doc.neutrino.utilities/topic/q/qcc.html)).

This maps internally as follows:
-stdlib= | -Y | Library
-- | -- | --
libc++ | _cxx | LLVM C++
libstdc++ | _gpp | GNU C++

Best regards.

**Comment by memsharded** [comment]
Hi @Johnnyxy 

Sorry this was not responded back then.

Conan 2 now defines the following:

```
qcc:
        version: ["4.4", "5.4", "8.3"]
        libcxx: [cxx, gpp, cpp, cpp-ne, accp, acpp-ne, ecpp, ecpp-ne]
        cppstd: [null, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17]
```
Is this ``libcxx`` enough? Thanks for the feedback
