### ISSUE TITLE
[bug] Github Actions — Not able to automatically detect 'cl' version

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#9612]
Hello,

I'm not able to install SDL2 on the Github Actions Windows agents — the Linux and MacOS work though.

I made sure `cl.exe` is available by running the `ilammy/msvc-dev-cmd@v1` task and then running `cl`. I also tried providing the `VS150COMNTOOLS` environment variable but neither of these helped Conan find the compiler.

Is there perhaps something I'm doing wrong in the pipeline setup, or missing a configuration option?

Thank you.

### Environment Details
  * Operating System+version: Windows Server 2019 on Github Actions
  * Compiler+version: CL 19.29.30133
  * Conan version: 1.40.1
  * Python version: 3.7.9

### Steps to reproduce
```
# conanfile.txt

[requires]
sdl/2.0.16

[generators]
cmake
```

```
# CMakeLists.txt

cmake_minimum_required(VERSION 3.00)
project(test)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS source/*.cpp)
add_executable(${PROJECT_NAME} ${SOURCES})

target_link_libraries(${PROJECT_NAME} PRIVATE ${CONAN_LIBS})
target_include_directories(${PROJECT_NAME} PRIVATE source)
set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
```

```
# pipeline.yml

name: ci

on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, cc: gcc }
          - { os: windows-latest, cc: cl }
          - { os: macos-latest, cc: clang }
    env:
      CC: ${{ matrix.config.cc }}
    steps:
      - uses: actions/checkout@v2
      - uses: turtlebrowser/get-conan@main
      - run: sudo apt-get install libegl-dev
        if: matrix.config.os == 'ubuntu-latest'
      - run: conan install conanfile.txt -if build
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
        if: matrix.config.cc == 'gcc'
      - run: cmake -B build
      - run: cmake --build build
```

### Logs
```
Run conan install conanfile.txt -if build
  conan install conanfile.txt -if build
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    CC: cl
Auto detecting your dev setup to initialize the default profile (C:\Users\runneradmin\.conan\profiles\default)
CC and CXX: cl, None 
Default settings
	os=Windows
	os_build=Windows
	arch=x86_64
	arch_build=x86_64
	build_type=Release
*** You can change them in C:\Users\runneradmin\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

sdl/2.0.16: Not found in local cache, looking in remotes...
sdl/2.0.16: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
sdl/2.0.16: Downloaded recipe revision 0
ERROR: Not able to automatically detect 'cl' version
ERROR: Unable to find a working compiler
WARN: Remotes registry file missing, creating default one in C:\Users\runneradmin\.conan\remotes.json
ERROR: sdl/2.0.16: 'settings.compiler' value not defined
Error: Process completed with exit code 1.
```
