### ISSUE TITLE
[question] How to install a local recipe with multiple versions

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9786]
https://github.com/bincrafters/community/tree/main/recipes/wxwidgets

config.yml
```yml
versions:
  "3.1.3":
    folder: "3.1.3"
  "3.1.4":
    folder: "all"
  "3.1.5":
    folder: "all"
```

How to install for version 3.1.5 with a local recipe?
